' Gambas module file

Public Sub Main()

  Dim hClient As New SmtpClient
  
  hClient.Host = "smtp.gmail.com"
  hClient.Encrypt = Net.SSL
  hClient.User = "g4mba5@gmail.com"
  Print "Password:";
  Line Input hClient.Password
  hClient.Debug = True
  
  hClient.Subject = "Test d'un sujet en UTF-8: == l'histoire d'un tout petit bébé =="
  hClient.From = "benoit@minisini.fr"
  hClient.To.Add("Benoît Minisini <benoit.minisini@gmail.com>")
  hClient.Body = "This is a test e-mail.\nI hope it will work...\n\nIl était une fois un tout petit bébé   \n=====\nJOLI HISTOIRE.\n  Il y a une pièce jointe !"
  hClient.Add(File.Load("~/TexteDehorsilpleut.odt"), "application/vnd.oasis.opendocument.text", "Dehors il pleut.odt")
  hClient.Add(File.Load("~/Zeno.png"), "image/png", "zeno.png")
  hClient.Send

End
