' Gambas module file

' Description:
' ScreenFunc.module
' Provides various screen related functions.

' Development Status:
' Imported from Kris's own project, needs testing.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2010 Ron Klinkien

' This module is Written and Copyrighted by Kris Wauters on February, 7th - 2010
' For more info or help, mailto: kris@digitalplayground.be

' Read file called COPYING for license details.

PUBLIC IntPassedKey AS Integer

'--- initialises a filterscreen dynamically ---
PUBLIC SUB InitFilterscreen(Frm AS Form)

  '--- declare variables ---
  DIM IntI, IntNumCols AS Integer
  DIM oObj1, oObj2, oObj3, oObj4, oObj5 AS Object
  DIM ColVw AS ColumnView
  DIM CmbObj AS ComboBox
  DIM rRes AS result

  '--- first, get number of columns equally to filter ---
  IntI = 0
  FOR EACH oObj1 IN Frm.Children
    IF UCase(Main.ParseTag(Object.GetProperty(oObj1, "Tag"), 2, "|")) = "FILTER" THEN
      '--- houston, we found our filterframe, so search for the filterbutton ---
      FOR EACH oObj2 IN oObj1.Children
        IF UCase(Main.ParseTag(Object.GetProperty(oObj2, "Tag"), 3, "|")) = "FILTER" THEN
          IntNumCols = Val(Main.ParseTag(Object.GetProperty(oObj2, "Tag"), 2, "|"))
          oObj5 = Frm.Children[IntI]
          BREAK
        END IF
      NEXT
    END IF
    INC IntI
  NEXT

  '--- next, get grid ---
  FOR EACH oObj2 IN Frm.Children
    IF UCase(Main.ParseTag(Object.GetProperty(oObj2, "Tag"), 2, "|")) = "RESULTS" THEN
      '--- houston, we found the results frame ---
      FOR EACH oObj3 IN oObj2.Children
        IF UCase(Object.Type(oObj3)) = "COLUMNVIEW" THEN
          '--- we have the gridview, now do some magic ---
          ColVw = oObj3
          ColVw.Columns.Count = IntNumCols
          FOR IntI = 0 TO IntNumCols - 1
            '--- lookup label, for columnheader text ---
            FOR EACH oObj4 IN oObj5.Children
              IF Val(Main.ParseTag(Object.GetProperty(oObj4, "Tag"), 2, "|")) = IntI THEN
                IF UCase(Object.Type(oObj4)) = "LABEL" THEN
                  ColVw.Columns[IntI].Text = Object.GetProperty(oObj4, "Text")
                ELSE
                  ColVw.Columns[IntI].Width = Object.GetProperty(oObj4, "Width")
                END IF
                '--- do something special with combo boxes (fill them up) :-) ---
                IF UCase(Object.Type(oObj4)) = "COMBOBOX" THEN
                  CmbObj = oObj4
                  FillCombo(CmbObj)
                END IF
              END IF
            NEXT
          NEXT
          BREAK
        END IF
      NEXT
    END IF
  NEXT
  ' --- Set security settings for current user, and put it in the tag of this form ---
  IF Main.bUserisAdmin THEN
    ' BtnAdd BtnView BtnModify BtnCopy rRes!BtnDelete rRes!BtnPrint rRes!PrinterName rRes!Orientation rRes!Color rRes!Copies
    Frm.Tag = "1|1|1|1|1|0|Default Printer|0|0|1"
  ELSE
    Frm.Tag = "0|1|0|0|0|0|Default Printer|0|0|1"
  END IF

END

'--- fill up a combobox, accordingly the defined tag ---
PUBLIC SUB FillCombo(Cmb AS Object)

  '--- declare variables ---
  DIM rRes AS Result

  Cmb.Clear
  Cmb.Add("")
  rRes = Main.hDB.Exec("SELECT " & Main.ParseTag(Cmb.tag, 4, "|") & " FROM " & Main.ParseTag(Cmb.tag, 3, "|") & " ORDER BY " & Main.ParseTag(Cmb.tag, 4, "|"))
  IF rRes THEN
    IF rRes.Count > 0 THEN
      FOR EACH rRes
        Cmb.Add(rRes[rRes.Fields[0].Name])
      NEXT
    END IF
  END IF
  rRes = NULL

END

'--- fillup columnview on filterscreen, accordingly given filter-data ---
PUBLIC SUB FilterData(FrmFilter AS frame, ColVw AS ColumnView, FrmBtns AS Frame, BtnFilter AS Button, FrmResult AS Frame)

  '--- declare variables ---
  DIM rRes AS result
  DIM IntCols, IntI, IntAnswer AS Integer
  DIM StrQuery, StrValue, StrFile AS String
  DIM StrType AS String[20]
  DIM Obj AS Object

  '--- init some variables ---
  ColVw.Clear
  IntCols = Val(Main.ParseTag(BtnFilter.Tag, 2, "|"))
  StrQuery = Main.ParseTag(BtnFilter.Tag, 4, "|")
  FrmResult.text = ("Resultset") & " [0]"

  '--- build-up query with all filterdata ---
  FOR IntI = 0 TO IntCols
    FOR EACH Obj IN FrmFilter.Children
      IF Val(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = IntI THEN
        SELECT CASE UCase(Object.Type(Obj))
          CASE "TEXTBOX"
            ColVw.Columns[IntI].width = Object.GetProperty(Obj, "Width")
            StrValue = Object.GetProperty(Obj, "Text")
            StrType[IntI + 1] = UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 3, "|"))
            SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 3, "|"))
              CASE "NUMERIC", "BOOLEAN"
                IF Trim(StrValue) = "" THEN StrValue = "0"
                IF Val(StrValue) > 0 THEN
                  StrQuery = StrQuery & " AND " & Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3) & " = " & Str(Val(StrValue))
                END IF
              CASE "TEXT", "DATE", "TIME", "DATETIME"
                IF Len(Trim(StrValue)) > 0 THEN
                  StrQuery = StrQuery & " AND " & Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3) & " like '%" & StrValue & "%'"
                END IF
              END SELECT
          CASE "COMBOBOX"
            StrType[IntI + 1] = "TEXT"
            ColVw.Columns[IntI].width = Object.GetProperty(Obj, "Width")
            StrValue = Object.GetProperty(Obj, "Text")
            IF Len(Trim(StrValue)) > 0 THEN
              StrQuery = StrQuery & " AND " & Main.ParseTag(Object.GetProperty(Obj, "Tag"), 4, "|") & " like '%" & StrValue & "%'"
            END IF
        END SELECT
      END IF
    NEXT
  NEXT

  '--- we have a (valid) query, so execute it ! ---
  rRes = Main.hDB.Exec(StrQuery)
  IF rRes THEN
    IF rRes.Count > 0 THEN
      IntAnswer = 1
      IF rRes.Count > 1000 THEN
        IntAnswer = Message.Question(("Your query results in more then 1000 items, continue ?"), ("Yes"), ("No"))
      END IF
      IF IntAnswer = 1 THEN
        FrmResult.text = ("Resultset") & " [" & CStr(rRes.count) & "]"
        FOR EACH rRes
          IF rRes.Fields.Count > IntCols + 1 THEN
            '--- if we have more fields, then we assume that the last 2 fields are for an icon ;-) ---
            StrFile = Main.BlobFromDB("SELECT * FROM " & Main.ParseTag(rRes.Fields[0].name, 1, ".") & " WHERE " & Main.ParseTag(rRes.Fields[0].Name, 2, ".") & " = " & rRes[rRes.Fields[0].Name], rRes.Fields[IntCols + 1].Name, rRes.Fields[IntCols + 2].Name)
            TRY ColVw.Add("K" & rRes[rRes.Fields[0].Name], "", Picture.Load(StrFile))
            IF ERROR THEN
              ColVw.Add("K" & rRes[rRes.Fields[0].Name], "")
            ENDIF
            TRY KILL StrFile
          ELSE
            ColVw.Add("K" & rRes[rRes.Fields[0].Name], "")
          END IF
          IF IntCols > 2 THEN
            ColVw.MoveTo("K" & rRes[rRes.Fields[0].Name])
            FOR IntI = 1 TO IntCols
              StrValue = rRes[rRes.Fields[IntI].Name]
              SELECT CASE StrType[IntI]
                CASE "DATETIME"
                  StrValue = Main.DateTimeFromSqlToApp(StrValue)
                CASE "DATE"
                  StrValue = Main.DateFromSQLToApp(StrValue)
                CASE "TIME"
                  StrValue = Main.TimeFromSQLToApp(StrValue)
                CASE "BOOLEAN"
                  IF StrValue = "1" THEN 
                    StrValue = "X"
                  ELSE
                    StrValue = ""
                  ENDIF
              END SELECT
              ColVw.Item[IntI - 1] = StrValue
            NEXT
          END IF
        NEXT
      END IF
    END IF
  ENDIF
  rRes = NULL

END

'--- set buttons, accordingly security settings and selection in colvw ---
PUBLIC SUB SetButtons(StrTag AS String, ColVw AS ColumnView, FrmBtns AS frame)

  '--- declare variables ---
  DIM BoolSet AS Boolean
  DIM IntI AS Integer
  DIM Obj AS Object

  BoolSet = FALSE
  '--- find if an item is selected or not ---
  IF ColVw.Current <> NULL THEN
    IF ColVw.Current.Selected = TRUE THEN
      BoolSet = TRUE
    ELSE
      BoolSet = FALSE
    ENDIF
  ELSE
    BoolSet = FALSE
  ENDIF

  '--- set command-buttons accordingly earlier retrieved security-settings ---
  FOR IntI = 1 TO 7
    FOR EACH Obj IN FrmBtns.Children
      IF Val(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 3, "|")) = IntI THEN
        SELECT CASE IntI
          '--- the add button ---
          CASE 1
            Object.SetProperty(Obj, "Enabled", CBool(Val(Main.ParseTag(StrTag, IntI, "|"))))
          '--- the "other" buttons ---
          CASE 2, 3, 4, 5
            IF CBool(Val(Main.ParseTag(StrTag, IntI, "|"))) = FALSE THEN
              Object.SetProperty(Obj, "Enabled", FALSE)
            ELSE
              Object.SetProperty(Obj, "Enabled", BoolSet)
            END IF
          '--- the print button ---
          CASE 6
            IF ColVw.Count > 0 THEN
              Object.SetProperty(Obj, "Enabled", CBool(Val(Main.ParseTag(StrTag, IntI, "|"))))
            ELSE
              Object.SetProperty(Obj, "Enabled", FALSE)
            END IF
          '--- the select button, no security settings ! ---
          CASE 7
            Object.SetProperty(Obj, "Enabled", BoolSet)
        END SELECT
      END IF
    NEXT
  NEXT

END

'--- show detailscreen from a given filter ---
PUBLIC SUB DoDetailScreen(StrAction AS String, ColVw AS ColumnView, FrmDetail AS form, StrTitle AS String)

  '--- declare variables ---
  DIM IntRecID AS Integer
  DIM rRes AS Result

  '--- do some initial settings ---
  IntRecID = 0
  FrmDetail.tag = Main.ParseTag(FrmDetail.tag, 1, "|") & "|" & Main.ParseTag(FrmDetail.tag, 2, "|") & "|" & StrAction
  FrmDetail.Title = StrTitle & " [" & (StrAction) & "]"

  '--- first, get RecID of selected item ---
  IF ColVw.Current <> NULL THEN
    IntRecID = Val(Right(ColVw.Current.Key, Len(ColVw.Current.Key) - 1))
  ENDIF

  '--- depending on "action", select data and put it on screen ---
  SELECT CASE UCase(StrAction)
    CASE "VIEW", "COPY", "MODIFY", "DELETE"
      rRes = Main.hDB.Exec(Main.ParseTag(FrmDetail.tag, 1, "|") & CStr(IntRecID))
      PutOnScreen(rRes, FrmDetail, StrAction)
    CASE "ADD"
      SetScreenForAdd(FrmDetail, StrAction)
  END SELECT
  FrmDetail.ShowModal

END

'--- we have a recordset an a detailscreen, now put the data on the screen, loop trough all controls recursively ! (part of DoDetailScreen) ---
PRIVATE SUB PutOnScreen(rRes AS result, FrmDetail AS Object, StrAction AS String)

  '--- declare variables ---
  DIM Obj AS Object
  DIM StrTmpFile AS String
  DIM rResTmp AS Result

  FOR EACH Obj IN FrmDetail.Children
    SELECT CASE UCase(Object.Type(Obj))
      CASE "CHECKBOX"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "BOOLEAN"
            IF CInt(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]) = 1 THEN
              Object.SetProperty(Obj, "Value", TRUE)
            ELSE
              Object.SetProperty(Obj, "Value", FALSE)
            END IF
            SetEnabled(Obj, StrAction)
        END SELECT
      CASE "TEXTBOX", "TEXTAREA"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "COLOR"
            IF Len(Trim(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)])) > 0 THEN
              Object.SetProperty(Obj, "BackColor", Val(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]))
            END IF
            SetEnabled(Obj, StrAction)
          CASE "TEXT", "NUMERIC"
            Object.SetProperty(Obj, "Text", rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)])
            SetEnabled(Obj, StrAction)
          CASE "QUERY"
            rResTmp = Main.hDB.Exec(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|") & rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)])
            Object.SetProperty(Obj, "Text", rResTmp[rResTmp.Fields[1].Name])
            Object.SetProperty(Obj, "Tag", Object.GetProperty(Obj, "Tag") & "|" & CStr(rResTmp[rResTmp.Fields[0].Name]))
            rResTmp = NULL
          CASE "FULLNAME"
            Object.SetProperty(Obj, "Text", rRes!FullName)
          CASE "RECID"
            Object.SetProperty(Obj, "Text", rRes!RecID)
          CASE "CREATIONDATE"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSqlToApp(rRes!CreationDate)) 
          CASE "MODIFICATIONDATE"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSqlToApp(rRes!ModificationDate)) 
          CASE "DATE"
            Object.SetProperty(Obj, "Text", Main.DateFromSQLToApp(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]))
            SetEnabled(Obj, StrAction)
          CASE "TIME"
            Object.SetProperty(Obj, "Text", Main.TimeFromSQLToApp(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]))
            SetEnabled(Obj, StrAction)
          CASE "DATETIME"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSQLToApp(rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]))
            SetEnabled(Obj, StrAction)
        END SELECT
      CASE "COMBOBOX"
        '--- write code to first fillup the combobox, and next set it to the correct item ---
        IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "TRUE"
          Object.SetProperty(Obj, "Tag", Object.GetProperty(Obj, "Tag") & "|" & rRes[Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3)]) 
          FillComboAndSet(Obj)
        END IF
      CASE "PICTUREBOX"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "BLOB"
            TRY StrTmpFile = Main.BlobFromDBWithResult(rRes, Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(Obj, "Name")) - 3), Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|"))
            TRY Object.SetProperty(Obj, "Picture", Picture.Load(StrTmpFile))
            TRY KILL StrTmpFile
        END SELECT
      CASE "BUTTON"
        IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "OK" OR UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "BROWSE" OR UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "CLEAR" THEN
          SELECT CASE UCase(StrAction)
            CASE "ADD", "MODIFY", "COPY", "DELETE"
              Object.SetProperty(Obj, "Enabled", TRUE)
            CASE "VIEW"
              Object.SetProperty(Obj, "Enabled", FALSE)
          END SELECT
        END IF
    END SELECT
    PutOnScreen(rRes, Obj, StrAction)
  NEXT
  FINALLY

END

'--- we need to return the RecID of the selected item in the combobox ---
PRIVATE FUNCTION GetComboID(Cmb AS Object) AS Integer

  '--- declare variables ---
  DIM rRes AS Result
  DIM StrTxt AS String

  StrTxt = Cmb.text
  rRes = Main.hDB.Exec("SELECT " & Main.ParseTag(Cmb.tag, 4, "|") & " FROM " & Main.ParseTag(Cmb.tag, 3, "|") & " ORDER BY " & Main.ParseTag(Cmb.tag, 4, "|"))
  IF rRes THEN
    IF rRes.Count > 0 THEN
      FOR EACH rRes
        IF rRes[rRes.Fields[0].Name] = StrTxt THEN
          RETURN CInt(rRes[rRes.Fields[1].Name])
        END IF
      NEXT
    END IF
  END IF
  rRes = NULL

END

'--- fill up a combobox, accordingly the defined TAG ---
PRIVATE SUB FillComboAndSet(Cmb AS Object)

  '--- declare variables ---
  DIM rRes AS Result
  DIM IntRecID AS Integer
  DIM StrFind AS String

  IntRecID = Main.ParseTag(Cmb.tag, 5, "|")
  Cmb.Clear
  Cmb.Add("")
  rRes = Main.hDB.Exec("SELECT " & Main.ParseTag(Cmb.tag, 4, "|") & " FROM " & Main.ParseTag(Cmb.tag, 3, "|") & " ORDER BY " & Main.ParseTag(Cmb.tag, 4, "|"))
  IF rRes THEN
    IF rRes.Count > 0 THEN
      FOR EACH rRes
        Cmb.Add(rRes[rRes.Fields[0].Name])
        IF CInt(rRes[rRes.Fields[1].Name]) = IntRecID THEN
          StrFind = rRes[rRes.Fields[0].Name]
        END IF
      NEXT
      Cmb.Index = Cmb.Find(Strfind)
    END IF
  END IF
  rRes = NULL

END

'--- special version for "add" action on detailscreen, loop trough all controls recursively ! (part of DoDetailScreen) ---
PRIVATE SUB SetScreenForAdd(FrmDetail AS Object, StrAction AS String)

  '--- declare variables ---
  DIM Obj AS Object

  FOR EACH Obj IN FrmDetail.Children
    SELECT CASE UCase(Object.Type(Obj))
      CASE "CHECKBOX"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "BOOLEAN"
            Object.SetProperty(Obj, "Value", FALSE)
            SetEnabled(Obj, StrAction)
        END SELECT
      CASE "TEXTBOX", "TEXTAREA"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "COLOR"
            SetEnabled(Obj, StrAction)
          CASE "TEXT", "NUMERIC"
            Object.SetProperty(Obj, "Text", "")
            SetEnabled(Obj, StrAction)
          CASE "FULLNAME"
            Object.SetProperty(Obj, "Text", "")
          CASE "RECID"
            Object.SetProperty(Obj, "Text", 0)
          CASE "CREATIONDATE"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSqlToApp("000000000000")) 
          CASE "MODIFICATIONDATE"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSqlToApp("000000000000")) 
          CASE "DATE"
            Object.SetProperty(Obj, "Text", Main.DateFromSQLToApp("00000000"))
            SetEnabled(Obj, StrAction)
          CASE "TIME"
            Object.SetProperty(Obj, "Text", Main.TimeFromSQLToApp("0000"))
            SetEnabled(Obj, StrAction)
          CASE "DATETIME"
            Object.SetProperty(Obj, "Text", Main.DateTimeFromSQLToApp("000000000000"))
            SetEnabled(Obj, StrAction)
        END SELECT
      CASE "COMBOBOX"
        '--- write code to first fillup the combobox, and next set it to the correct item ---
        IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "TRUE"
          FillCombo(Obj)
        ENDIF
      CASE "BUTTON"
        IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "OK" OR UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "BROWSE" OR UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "CLEAR" THEN
          SELECT CASE UCase(StrAction)
            CASE "ADD", "MODIFY", "COPY", "DELETE"
              Object.SetProperty(Obj, "Enabled", TRUE)
            CASE "VIEW"
              Object.SetProperty(Obj, "Enabled", FALSE)
          END SELECT
        END IF
    END SELECT
    SetScreenForAdd(Obj, StrAction)
  NEXT
  FINALLY

END

'--- set a control enabled or disabled, accordingly the given action for the detailscreen (part of DoDetailScreen and sub functions) ---
PRIVATE SUB SetEnabled(Obj AS Object, StrAction AS String)

  SELECT CASE UCase(StrAction)
    CASE "MODIFY", "COPY", "ADD"
      Object.SetProperty(Obj, "Enabled", TRUE)
    CASE "DELETE", "VIEW"
      Object.SetProperty(Obj, "Enabled", FALSE)
  END SELECT

END

'--- Do the action of the detailscreen, accordingly given action ---
PUBLIC FUNCTION ActionOnDetailScreen(Frm AS Form) AS Integer

  '--- declare variables ---
  DIM StrNameArray AS String[0]
  DIM StrValueArray AS String[0]
  DIM StrQuery AS String
  DIM IntI, IntRecID AS Integer
  DIM rRes AS Result

  '--- build array with all controls on the form, and the value they have ---
  BuildArrays(StrNameArray, StrValueArray, Frm)
  IntRecID = 0
  '--- next, build query, accordingly the given action for the detailscreen ---
  SELECT CASE UCase(Main.ParseTag(Frm.Tag, 3, "|"))
    CASE "ADD", "COPY"
      StrQuery = "INSERT INTO " & Main.ParseTag(Frm.Tag, 2, "|") & " ("
      FOR IntI = 0 TO StrNameArray.Count - 1
        IF StrNameArray[IntI] <> "CreationDate" AND StrNameArray[IntI] <> "ModificationDate" AND StrNameArray[IntI] <> "RecID" THEN
          StrQuery = StrQuery & StrNameArray[IntI] & ","
        END IF
      NEXT
      StrQuery = StrQuery & "CreationDate,ModificationDate,FK_Users) VALUES("
      FOR IntI = 0 TO StrNameArray.Count - 1
        IF StrNameArray[IntI] <> "CreationDate" AND StrNameArray[IntI] <> "ModificationDate" AND StrNameArray[IntI] <> "RecID" THEN
          StrQuery = StrQuery & StrValueArray[IntI] & ","
        END IF
      NEXT
      StrQuery = StrQuery & "'" & Format(Now, "yyyymmddhhnn") & "','" & Format(Now, "yyyymmddhhnn") & "'," & Main.sActiveUserID & ")"
    CASE "DELETE"
      StrQuery = "DELETE FROM " & Main.ParseTag(Frm.Tag, 2, "|") & " WHERE RecID = "
      FOR IntI = 0 TO StrNameArray.Count - 1
        IF StrNameArray[IntI] = "RecID" THEN
          StrQuery = StrQuery & StrValueArray[IntI]
          IntRecID = 0
          BREAK
        END IF
      NEXT
    CASE "MODIFY"
      StrQuery = "UPDATE " & Main.ParseTag(Frm.Tag, 2, "|") & " SET "
      FOR IntI = 0 TO StrNameArray.Count - 1
        IF StrNameArray[IntI] <> "ModificationDate" AND StrNameArray[IntI] <> "RecID" THEN
          StrQuery = StrQuery & StrNameArray[IntI] & "=" & StrValueArray[IntI] & ","
        END IF
      NEXT
      StrQuery = StrQuery & "ModificationDate='" & Format(Now, "yyyymmddhhnn") & "',FK_Users=" & Main.sActiveUserID & " WHERE RecID = "
      FOR IntI = 0 TO StrNameArray.Count - 1
        IF StrNameArray[IntI] = "RecID" THEN
          StrQuery = StrQuery & StrValueArray[IntI]
          IntRecID = Val(StrValueArray[IntI])
          BREAK
        END IF
      NEXT
  END SELECT

  '--- finally, execute the query, and close the form ---
  Main.hDB.Exec(StrQuery)
  '--- when ADD or COPY, lookup new RecID ---
  IF (Main.ParseTag(Frm.Tag, 3, "|")) = "ADD" OR (Main.ParseTag(Frm.Tag, 3, "|")) = "COPY" THEN
    rRes = Main.hDB.Exec("SELECT LAST_INSERT_ID()")
    IF rRes THEN
      IF rRes.Count > 0 THEN
        IntRecID = CInt(rRes[rRes.Fields[0].Name])
      END IF
    END IF
  END IF
  rRes = NULL
  '--- return RecID ---
  RETURN IntRecID

END

'--- loop trough all controls on the given form, and create and array with names & values (part of ActionOnDetailScreen) ---
PRIVATE SUB BuildArrays(StrNameArray AS String[], StrValueArray AS String[], Frm AS Object)

  '--- declare variables ---
  DIM Obj AS Object

  '--- loop trough all children, and put data in array ---
  FOR EACH Obj IN Frm.Children
    SELECT CASE UCase(Object.Type(Obj))
      CASE "CHECKBOX"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "BOOLEAN"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            IF Object.GetProperty(Obj, "Value") = TRUE THEN
              StrValueArray.Add("1")
            ELSE
              StrValueArray.Add("0")
            END IF
        END SELECT
      CASE "TEXTBOX", "TEXTAREA"
        SELECT CASE UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 1, "|"))
          CASE "COLOR"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add("'" & Object.GetProperty(Obj, "BackColor") & "'")
          CASE "TEXT"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add("'" & Object.GetProperty(Obj, "Text") & "'")
          CASE "QUERY"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 3, "|"))
          CASE "NUMERIC"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add(Object.GetProperty(Obj, "Text"))
          CASE "RECID"
            StrNameArray.add("RecID")
            StrValueArray.Add(Object.GetProperty(Obj, "Text"))
          CASE "CREATIONDATE"
            StrNameArray.add("CreationDate")
            StrValueArray.Add("'" & Main.DateTimeFromAppToSQL(Object.GetProperty(Obj, "Text")) & "'")
          CASE "DATE"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add("'" & Main.DateFromAppToSQL(Object.GetProperty(Obj, "Text")) & "'")
          CASE "TIME"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add("'" & Main.TimeFromAppToSql(Object.GetProperty(Obj, "Text")) & "'")
          CASE "DATETIME"
            StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
            StrValueArray.Add("'" & Main.DateTimeFromAppToSQL(Object.GetProperty(Obj, "Text")) & "'")
        END SELECT
      CASE "COMBOBOX"
        '--- write code to retrieve ID from selected combobox item ---
        IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "TRUE" THEN
          StrNameArray.add(Right(Object.GetProperty(Obj, "Name"), Len(Object.GetProperty(obj, "Name")) - 3))
          StrValueArray.Add(GetComboID(Obj))
        END IF
    END SELECT
    BuildArrays(StrNameArray, StrValueArray, Obj)
  NEXT
  FINALLY

END

'--- do printfunction for filterdata ---
PUBLIC SUB PrintFilter(FrameFilter AS Frame, ColVw AS ColumnView, StrTitle AS String, StrTag AS String)

  '--- declare variables ---
  DIM StrFile AS String

  '--- creating html file ---
  StrFile = CreateHTMLFile(FrameFilter, ColVw, StrTitle)
  '--- first, convert to PDF (htmldoc needs to be installed !), next print trough lpr ---
  '--- printing keeps in mind: color/gray - landscape/portrait - printername - number of copies (all this can be different for every screen and every user) ---
  PrintHTMLFile(StrFile, Main.ParseTag(StrTag, 7, "|"), Val(Main.ParseTag(StrTag, 8, "|")), Val(Main.ParseTag(StrTag, 9, "|")), Val(Main.ParseTag(StrTag, 10, "|")))

END

'--- create a HTML file, based on the filterdata (part of PrintFilter) ---
PRIVATE FUNCTION CreateHTMLFile(FrameFilter AS Frame, ColVw AS ColumnView, StrTitle AS String) AS String

  '--- declare variables ---
  DIM StrHTML, StrFile, StrImgFile, StrExtra AS String
  DIM IntI AS Integer
  DIM Obj AS Object

  '--- header ---
  StrHTML = "<html><head></head>" & gb.NewLine
  StrHTML = StrHTML & "<!--" & gb.NewLine
  StrHTML = StrHTML & "<style type='text/css'> .inhoud {font-family: Tahoma, Geneva, sans-serif;font-size: 9px;}" & gb.NewLine
  StrHTML = StrHTML & ".header2 {font-family: Tahoma, Geneva, sans-serif;font-size: 14px;}</style>" & gb.NewLine
  StrHTML = StrHTML & "-->" & gb.NewLine
  StrHTML = StrHTML & "<body><table width='100%' border='0' cellspacing='0' cellpadding='5'><tr><td align=left class='inhoud'>"
  StrHTML = StrHTML & "<font color='FF0000'>[" & Main.sActiveUserID & "] " & StrTitle & "</font></td><td align=right class='inhoud'><i>" & ("Printed by") & " " & Main.sActiveUser & "</i></td></tr></table>" & gb.NewLine
  StrHTML = StrHTML & "<table width='100%' border='01' cellspacing='0' cellpadding='5'><tr><td colspan=" & CStr(ColVw.Columns.Count) & " align=center class='header2'><b><H3><font color='0000FF'>" & ("Filter Criteria") & "</font></H3></b></td></tr><tr>" & gb.NewLine
  '--- filter header ---
  FOR IntI = 0 TO ColVw.Columns.Count - 1
    StrHTML = StrHTML & "<td class='inhoud'><H5><font color='0000FF'>" & ColVw.Columns[IntI].text & "</font></H5></td>" & gb.NewLine  
  NEXT
  '--- add layout item for new tablerow ---
  StrHTML = StrHTML & "</tr><tr>" & gb.NewLine
  '--- filter data ---
  FOR IntI = 0 TO ColVw.Columns.Count - 1
    FOR EACH Obj IN FrameFilter.Children
      IF Val(Main.ParseTag(Object.GetProperty(obj, "Tag"), 2, "|")) = IntI AND Object.Type(Obj) <> "Label" THEN
        IF Len(Trim(Object.GetProperty(Obj, "Text"))) > 0 THEN
          StrHTML = StrHTML & "<td class='inhoud'><H6>" & Trim(Object.GetProperty(Obj, "Text")) & "</H6></td>" & gb.NewLine
        ELSE
          StrHTML = StrHTML & "<td class='inhoud'><H6><br></H6></td>" & gb.NewLine
        END IF
      END IF
    NEXT
  NEXT
  '--- count lines in result ColumnView ---
  IntI = 0
  ColVw.MoveFirst
  WHILE ColVw.Item <> NULL
    IntI = IntI + 1
    ColVw.MoveBelow
  WEND
  '--- fixed layout part ---
  StrHTML = StrHTML & "</tr><tr><td colspan=" & CStr(ColVw.Columns.Count) & " align=center class='header2'><b><H3><font color='0000FF'>" & CStr(IntI) & " " & ("Results") & "</font></H3></b></td></tr><tr>" & gb.NewLine
  '--- result header ---
  FOR IntI = 0 TO ColVw.Columns.Count - 1
    StrHTML = StrHTML & "<td class='inhoud'><b><H5><font color='0000FF'>" & ColVw.Columns[IntI].text & "</font></H5></b></td>" & gb.NewLine
  NEXT
  '--- add layout item for new tablerow ---
  StrHTML = StrHTML & "</tr>" & gb.NewLine
  '--- add result data ---
  ColVw.MoveFirst
  WHILE ColVw.Item <> NULL
    StrHTML = StrHTML & "<tr>" & gb.NewLine
    FOR IntI = 0 TO ColVw.Columns.Count - 1
      StrExtra = ""
      IF IntI = 0 THEN
        IF ColVw.Item.Picture <> NULL THEN
          StrImgFile = Temp() & ".png"
          ColVw.Item.Picture.Image.Save(StrImgFile)
          StrExtra = "<img src='" & StrImgFile & "'>"
        END IF
      END IF
      IF Len(Trim(ColVw.Item[IntI])) > 0 THEN
        StrHTML = StrHTML & "<td class='inhoud'><H6>" & StrExtra & Trim(ColVw.Item[IntI]) & "</H6></td>"
      ELSE
        StrHTML = StrHTML & "<td class='inhoud'><H6>" & StrExtra & "<br></H6></td>"
      ENDIF
    NEXT
    ColVw.MoveBelow
    StrHTML = StrHTML & "</tr>" & gb.NewLine
  WEND
  '--- footer ---
  StrHTML = StrHTML & "</table></body></html>"
  '--- write StrHtml to tempfile ---
  StrFile = Temp() & ".html"
  File.Save(StrFile, StrHtml)
  RETURN StrFile

END

'--- convert the created HTML file to PDF, and then print the PDF (part of PrintFilter) ---
PRIVATE SUB PrintHTMLFile(StrHTMLFile AS String, StrPrinterName AS String, IntOrientation AS Integer, IntColor AS Integer, IntCopies AS Integer)

  '--- declare variables ---
  DIM StrPDFFile, StrExtraPDF AS String

  '--- set some variables ---
  StrPDFFile = Temp() & ".pdf"
  IF IntOrientation = 0 THEN
    StrExtraPDF = "--portrait"
  ELSE
    StrExtraPDF = "--landscape"
  ENDIF
  IF IntColor = 0 THEN
    StrExtraPDF = StrExtraPDF & " --gray"
  ELSE
    StrExtraPDF = StrExtraPDF & " --color"
  ENDIF
  '--- convert to PDF ---
  SHELL "htmldoc " & StrExtraPDF & " -t pdf14 --continuous --no-jpeg --no-compression --footer " & Chr(34) & "D /" & Chr$(34) & " --outfile " & StrPDFFile & " --webpage " & StrHTMLFile WAIT
  '--- print the PDF ---
  SHELL "lpr -P " & StrPrinterName & " -# " & CStr(IntCopies) & " " & StrPDFFile WAIT
  '--- delete the HTML & PDF file ---
  KILL StrHTMLFile
  KILL StrPDFFile

END

'--- put a picture into SQL DB, based on detailscreen ---
PUBLIC SUB BlobOnDetailScreen(IntRecID AS Integer, StrFrmTag AS String, PicBLOBicon AS PictureBox)

  '--- declare variables ---
  DIM StrTmpFile AS String

  StrTmpFile = Temp() & ".PNG"
  TRY PicBLOBicon.Picture.Save(StrTmpFile)
  IF ERROR THEN
    '--- there is no picture ---
    WAIT 0.01
  ELSE
    Main.BlobToDB(Main.ParseTag(StrFrmTag, 2, "|"), "RecID=&1", IntRecID, Right(PicBLOBicon.Name, Len(PicBLOBicon.Name) - 3), Main.ParseTag(PicBLOBicon.Tag, 2, "|"), StrTmpFile)
    KILL StrTmpFile
  END IF

END

'--- show a filter, make a selection, and process it ! ---
PUBLIC SUB DoQuery(TxtField AS TextBox, FrmDetail AS Form)

  '--- declare variables ---
  DIM rRes AS Result

  IntPassedKey = 0
  VisibilitySelectBtn(FrmDetail, TRUE)
  FrmDetail.ShowModal
  VisibilitySelectBtn(FrmDetail, FALSE)
  IF IntPassedKey > 0 THEN
    '--- change text and tag of TxtField ---
    TxtField.tag = Main.ParseTag(TxtField.Tag, 1, "|") & "|" & Main.ParseTag(TxtField.Tag, 2, "|") & "|" & CStr(IntPassedKey)
    rRes = Main.hDB.Exec(Main.ParseTag(TxtField.tag, 2, "|") & CStr(IntPassedKey))
    TxtField.Text = rRes[rRes.Fields[1].Name]
    rRes = NULL
  END IF

END

'--- search for the select button on a filterscreen, and make it visible or invisible ---
PRIVATE SUB VisibilitySelectBtn(ObjDetail AS Object, BoolVisible AS Boolean)

  '--- declare variables ---
  DIM Obj AS Object

  FOR EACH Obj IN ObjDetail.Children
    IF UCase(Object.Type(Obj)) = "BUTTON" THEN
      IF UCase(Main.ParseTag(Object.GetProperty(Obj, "Tag"), 2, "|")) = "SELECT" THEN
        Object.SetProperty(Obj, "Visible", BoolVisible)
      END IF
    END IF
    VisibilitySelectBtn(Obj, BoolVisible)
  NEXT
  FINALLY

END

'--- set the IntPassedKey to the selected value of a columnview of a filterscreen ---
PUBLIC SUB SetKey(ColVw AS ColumnView, Frm AS Form)

  IntPassedKey = Val(Right(ColVw.Current.Key, Len(ColVw.Current.Key) - 1))
  Frm.Close

END