' Gambas module file

' Description:
' Client.module
' Only created to make transistion from XML-RPC to JSON-RPC easier

' Development Status:
' Working

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ModuleRestart(sModule As String)
  Try Object.Call(Main.hRPCType, "ModuleRestart", [sModule])
  Try Plugin.Restart(sModule, 1)
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendEmail(sTo As String, sSubject As String, sBody As String)
  Try Object.Call(Main.hRPCType, "SendEmail", [sTo, sSubject, sBody])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendTweet(sText As String)
  Try Object.Call(Main.hRPCType, "SendTweet", [sText])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendSMS(sTo As String, sText As String)
  Try Object.Call(Main.hRPCType, "SendSMS", [sTo, sText])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetHouseMode(sMode As String)
  Try Object.Call(Main.hRPCType, "SetHouseMode", [sMode])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetMuteMode(bMode As Boolean)
  Try Object.Call(Main.hRPCType, "SetMuteMode", [bMode])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DeviceSetDevice(sDevice As Integer, sValue As String)
  Try Object.Call(Main.hRPCType, "DeviceSetDevice", [sDevice, sValue])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateServerStatsGraphs(sRange As String)
  Try Object.Call(Main.hRPCType, "UpdateServerStatsGraphs", [sRange])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CreateRRDs(iId As Integer)
  Try Object.Call(Main.hRPCType, "CreateRRDs", [iId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateRRDGraphs(sGroup As String, sRange As String)
  Try Object.Call(Main.hRPCType, "UpdateRRDGraphs", [sGroup, sRange])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmPin(sPin As String)
  Try Object.Call(Main.hRPCType, "SetAlarmPin", [sPin])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmMode(sMode As String)
  Try Object.Call(Main.hRPCType, "SetAlarmMode", [sMode])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PlaySound(sSound As String, iVolume As Integer)
  Try Object.Call(Main.hRPCType, "PlaySound", [sSound, iVolume])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function VoiceTextSpeak(sText As String, sVoice As String)
  Try Object.Call(Main.hRPCType, "VoiceTextSpeak", [sText, sVoice])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DisplayLEDMessage(sId As String, sText As String)
  Try Object.Call(Main.hRPCType, "DisplayLEDMessage", [sId, sText])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVSetControl(sModel As String, sCmd As String, sValue As String, sAddress As String)
  Try Object.Call(Main.hRPCType, "AVSetControl", [sModel, sCmd, sValue, sAddress])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVGetControl(sModel As String, sCmd As String, sAddress As String)
  Try Object.Call(Main.hRPCType, "AVGetControl", [sModel, sCmd, sAddress])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetGlobalVars() As Boolean
  Try Return Object.Call(Main.hRPCType, "GetGlobalVars")
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetGlobalVar(sVar As String, sValue As String, vValue As Variant, Optional sDataType As String = "")
  If sDataType Then
    Try Object.Call(Main.hRPCType, "SetGlobalVar", [sVar, sValue, vValue, sDataType])
  Else
    Try Object.Call(Main.hRPCType, "SetGlobalVar", [sVar, sValue, vValue])
  Endif
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DelGlobalVar(sVar As String)
  Try Object.Call(Main.hRPCType, "DelGlobalVar", [sVar])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULSimulate(sPacket As String)
  Try Object.Call(Main.hRPCType, "CULSimulate", [sPacket])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULQueueCommand(sPacket As String)
  Try Object.Call(Main.hRPCType, "CULQueueCommand", [sPacket])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PLCBUSTXCommand(sAddress As String, sCmd As String, bAck As Boolean, bData As Byte)
  Try Object.Call(Main.hRPCType, "PLCBUSTXCommand", [sAddress, sCmd, bAck, bData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunActions(iEventId As Integer)
  Try Object.Call(Main.hRPCType, "RunActions", [iEventId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunAction(cData As Collection) As Boolean
  Try Return Object.Call(Main.hRPCType, "RunAction", [cData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Condition_Eval(cData As Collection) As String
  Try Return Object.Call(Main.hRPCType, "Condition_Eval", [cData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub GetProgramVersion() As String
  Try Return Object.Call(Main.hRPCType, "GetProgramVersion")
End

Public Function GetPlanning()
  Try Object.Call(Main.hRPCType, "GetPlanning")
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetPlanning()
  Try Object.Call(Main.hRPCType, "SetPlanning")
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxSetVolumePlayer(sPlayerId As String, sVolume As String)
  Try Object.Call(Main.hRPCType, "SqueezeboxSetVolumePlayer", [sPlayerId, sVolume])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetVolumePlayer(sPlayerId As String) As String
  Try Object.Call(Main.hRPCType, "SqueezeboxGetVolumePlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxStopPlayer(sPlayerId As String)
  Try Object.Call(Main.hRPCType, "SqueezeboxStopPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPlayPlayer(sPlayerId As String)
  Try Object.Call(Main.hRPCType, "SqueezeboxPlayPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxNextNumberPlayer(sPlayerId As String)
  Try Object.Call(Main.hRPCType, "SqueezeboxNextNumberPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPrevNumberPlayer(sPlayerId As String)
  Try Object.Call(Main.hRPCType, "SqueezeboxPrevNumberPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentTitlePlayer(sPlayerId As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetCurrentTitlePlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetModePlayer(sPlayerId As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetModePlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerId(sPlayerIndex As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetPlayerId", [sPlayerIndex])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerName(sPlayerIndex As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetPlayerName", [sPlayerIndex])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayer(sPlayerIndex As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetIsPlayer", [sPlayerIndex])
End 
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetAlbums() As String[]
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetAlbums")
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxClearPlaylistPlayer(sPlayerId As String) As Boolean
  Try Return Object.Call(Main.hRPCType, "SqueezeboxClearPlaylistPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxAddAlbumToPlaylistPlayer(sPlayerId As String, sAlbumName As String) As Boolean
  Try Return Object.Call(Main.hRPCType, "SqueezeboxAddAlbumToPlaylistPlayer", [sPlayerId, sAlbumName])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentArtistPlayer(sPlayerId As String) As String
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetCurrentArtistPlayer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayerConnectedToServer(sPlayerId As String) As Boolean
  Try Return Object.Call(Main.hRPCType, "SqueezeboxGetIsPlayerConnectedToServer", [sPlayerId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatDerogateHeating(iScenarioId As String, iHeatingId As String, sOperator As String) As Boolean
  Try Return Object.Call(Main.hRPCType, "ThermostatDerogateHeating", [iScenarioId, iHeatingId, sOperator])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatGetDerogateHeating(iHeatingId As String) As Float
  Try Return Object.Call(Main.hRPCType, "ThermostatGetDerogateHeating", [iHeatingId])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ToolsOpenZWaveGet(sCommand As String, Optional iInstance As Integer = 0) As Variant
  Try Return Object.Call(Main.hRPCType, "ToolsOpenZWaveGet", [sCommand, iInstance])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ToolsOpenZWaveSet(cData As Collection) As Variant
  Try Return Object.Call(Main.hRPCType, "ToolsOpenZWaveSet", [cData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_RFXCom_Get(cData As Collection) As Variant
  Try Return Object.Call(Main.hRPCType, "Call_Tools_RFXCom_Get", [cData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_RFXCom_Set(cData As Collection) As Variant
  Try Return Object.Call(Main.hRPCType, "Call_Tools_RFXCom_Set", [cData])
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_SerialPort_Get(cData As Collection) As Variant
  Try Return Object.Call(Main.hRPCType, "Call_Tools_SerialPort_Get", [cData])
End

