' Gambas module file

' Description:
' Client.module
' Support for client/server setup via JSON-RPC interface.

' Development Status:
' Working

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public LogLabel As String = "[Client] "
Public $bDebug As Boolean = True
Public $sURL As String = "localhost:9090"

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Generic JSON RPC Client procedure
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_JsonRpcClient(sMethod As String, bAsync As Boolean, cData As JSONCollection) As Variant

  Dim cRpc As JsonRpcClient
  Dim bOk As Boolean

  If $bDebug Then Main.WriteDebugLog(LogLabel & "Method=" & sMethod)

  cRpc = New JsonRpcClient(sMethod) As "cRpc"
  cRpc.URL = $sURL
  cRpc.Async = bAsync
  bOk = cRpc.Call(cData)

  ' If Async = True then just check we got bOk, then the call start successfully
  ' If Async = False then we need to check bOk and then the Reply variable for the information
  If bAsync Then
    If Not bOk Then
      Main.WriteLog(LogLabel & "ERROR: Method: '" & cRpc.Method & "' returned '" & cRpc.ErrorMsg & "'.")
      Return
    Endif
  Else
    If bOk Then
      Return Process_JsonRpc_Reply(cRpc, cRpc.Reply)
    Else
      Main.WriteLog(LogLabel & "ERROR: '" & cRpc.ErrorMsg & "' when posting to URL '" & cRpc.URL & "'. Method: '" & cRpc.Method & "'.")
      Return Null
    Endif 
  Endif

Catch
  Main.WriteLog(LogLabel & "ERROR: '" & Error.Text & "' at " & Error.Where & "', when posting to URL '" & cRpc.URL & "'. Method: '" & cRpc.Method & "'")

End

Public Sub cRpc_Reply(vReply As Variant)

  Process_JsonRpc_Reply(Last, vReply)

End

Public Sub cRpc_BadReply(sText As String)

  Main.WriteLog(LogLabel & "ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. Method: '" & Last.Method & "'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Process response for almost all methods
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Private Sub Process_JsonRpc_Reply(cRpc As Object, vReply As Variant) As Variant

  Dim vValue As Variant

  Select cRpc.Method
    Case "domotiga.version"
      FMain.CheckServerVersion(vReply)

    Case "plugin.restart"
      If vReply Then
      Main.WriteLog(LogLabel & "Successfully (re)started plugin on server.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem (re)starting plugin on server, check it's log.")
      Endif

    Case "globalvar.list"

      ' Reset the GlobalVars before we start filling it again
      Main.RestoreGlobalVars(False)

      If vReply Then
        For Each vValue In vReply
          Main.SetGlobalVar(vReply.Key, vValue)
        Next
      Endif

    Case "globalvar.set"
      If vReply Then
        If TypeOf(cRpc.Params["value"]) = gb.Boolean Then
          Main.WriteLog(LogLabel & "Successfully set '" & cRpc.Params["name"] & "' to '" & IIf(cRpc.Params["value"], "True", "False") & "'.")
        Else
          Main.WriteLog(LogLabel & "Successfully set '" & cRpc.Params["name"] & "' to '" & cRpc.Params["value"] & "'.")
        Endif
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem setting '" & cRpc.Params["name"] & "', message '" & cRpc.ErrorMsg & "'.")
      Endif

    Case "housemode.set"
      If vReply Then
        If cRpc.Params["mode"] Then
          Main.WriteLog(LogLabel & "Successfully set House mode to '" & cRpc.Params["mode"] & "'.")
        Else
          Main.WriteLog(LogLabel & "Successfully set Mute mode to '" & IIf(cRpc.Params["mute"], "Audio Disabled", "Audio Enabled") & "'.")
        Endif
      Else
        If cRpc.Params["mode"] Then
          Main.WriteLog(LogLabel & "ERROR: There was a problem setting House mode to '" & cRpc.Params["mode"] & "'.")
        Else
          Main.WriteLog(LogLabel & "ERROR: There was a problem setting Mute mode to '" & cRpc.Params["mute"] & "'.")
        Endif
      Endif

    Case "email.send"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully sent e-mail to '" & cRpc.Params["to"] & "'.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem sending e-mail to " & cRpc.Params["to"] & ".")
      Endif

    Case "twitter.send"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully sent tweet.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem sending tweet.")
      Endif

    Case "sms.send"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully sent SMS to '" & cRpc.Params["to"] & "'.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem sending SMS to '" & cRpc.Params["to"] & "'.")
      Endif

    Case "device.set"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem setting value of device!")

    Case "sound.play"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem playing sound.")

    Case "voicetext.play"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem speaking voicetext.")

    Case "serverstat.update"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem updating serverstats graphs.")

    Case "rrdtool.create"
        If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem creating rrdtool databases.")
    Case "rrdtool.update"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem updating rrdtool graphs.")
    Case "rrdtool.generate"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem generating the rrdtool graph.")
    Case "rrdtool.deleterrd"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem deleting the rrd file(s).")

    Case "dsc.setpin"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully set DSC Alarm pin.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem setting DSC Alarm pin.")
      Endif
    Case "dsc.setalarm"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully set DSC Alarm mode.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem setting DSC Alarm mode.")
      Endif

    Case "ledmatrix.display"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem displaying LEDMatrix message.")

    Case "avcontrol.get"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem controlling audio/video device '" & cRpc.Params["model"] & "' with '" & cRpc.Params["cmd"] & "'.")

    Case "avcontrol.set"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem getting audio/video device settngs '" & cRpc.Params["model"] & "' with '" & cRpc.Params["cmd"] & "'.")

    Case "cul.simulate"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem simulating CUL packet '" & cRpc.Params["data"] & "'.")

    Case "cul.queuecommand"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem queueing CUL command '" & cRpc.Params["cmd"] & "'.")

    Case "calendar.get"
      Calendar.dPlanning.Clear()
      If vReply Then
        For Each vValue In vReply
          Try Calendar.dPlanning.Add(CDate(vValue))
        Next
      Endif

    Case "calender.set"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully set occupancy planning.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem setting ocupancy planning.")
      Endif

    Case "event.run"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully executed actions from event with id '" & cRpc.Params["event_id"] & "'.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem executing actions from event with id '" & cRpc.Params["event_id"] & "'.")
      Endif

    Case "action.run"
      If vReply Then
        Main.WriteLog(LogLabel & "Successfully executed action with id '" & cRpc.Params["action_id"] & "'.")
      Else
        Main.WriteLog(LogLabel & "ERROR: There was a problem executing action with id '" & cRpc.Params["action_id"] & "'.")
      Endif

    Case "squeezebox.set"
      If vReply Then
        Select cRpc.Params["function"]
          Case "volume"
            Main.WriteLog(LogLabel & "Successfully set volume player '" & cRpc.Params["player"] & "'.")
          Case "startplayer"
            Main.WriteLog(LogLabel & "Successfully set play player '" & cRpc.Params["player"] & "'.")
          Case "stopplayer"
            Main.WriteLog(LogLabel & "Successfully set stop player '" & cRpc.Params["player"] & "'.")
          Case "nextnumber"
            Main.WriteLog(LogLabel & "Successfully set next number player '" & cRpc.Params["player"] & "'.")
          Case "prevnumber"
            Main.WriteLog(LogLabel & "Successfully set prev number player '" & cRpc.Params["player"] & "'.")
          Case "clearplaylist"
            Main.WriteLog(LogLabel & "Successfully set clear playlist player '" & cRpc.Params["player"] & "'.")
          Case "addalbumtoplaylist"
            Main.WriteLog(LogLabel & "Successfully set add album to playlist player '" & cRpc.Params["player"] & "'.")
        End Select
      Else
        Select cRpc.Params["function"]
          Case "volume"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to set volume player '" & cRpc.Params["player"] & "'.")
          Case "startplayer"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to set play player '" & cRpc.Params["player"] & "'.")
          Case "stopplayer"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to set stop player '" & cRpc.Params["player"] & "'.")
          Case "nextnumber"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to set next number player '" & cRpc.Params["player"] & "'.")
          Case "prevnumber"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to set prev number player '" & cRpc.Params["player"] & "'.")
          Case "clearplaylist"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to clear playlistplayer '" & cRpc.Params["player"] & "'.")
          Case "addalbumtoplaylist"
            Main.WriteLog(LogLabel & "ERROR: There was a problem to add a ablum to playlist player '" & cRpc.Params["player"] & "'.")
        End Select
      Endif
    Case "squeezebox.get"
    'Main.WriteLog(LogLabel & "Successfully get current artist player '" & sPlayerId & "'.")
    'Main.WriteLog(LogLabel & "ERROR: There was a problem to get current artist player '" & sPlayerId & "'.")
    'Main.WriteLog(LogLabel & "Successfully player is connected to server player id '" & sPlayerId & "'.")
    'Main.WriteLog(LogLabel & "ERROR: There was a problem to get player is connected to server player id '" & sPlayerId & "'.")

    Case "thermostat.derogateheating"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem derogating heating.")

    Case "cmdr.plcbus.txcommand"
      If Not vReply Then Main.WriteLog(LogLabel & "ERROR: There was a problem sending PLCBUS command for '" & cRpc.Params["address"] & "'.")

  End Select

  Return vReply

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Retrieve program version from the server
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetProgramVersion()

  Call_JsonRpcClient("domotiga.version", True, Null)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Restart Plugin
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Plugin_Restart(sPlugin As String, Optional iInstance As Integer = 1)

  Dim cData As New JSONCollection

  cData.Add(sPlugin, "name")
  cData.Add(iInstance, "instance_id")
  Call_JsonRpcClient("plugin.restart", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Get all global variables
' True=Call was successfull, False=An error occured
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetGlobalVars() As Boolean

  If Call_JsonRpcClient("globalvar.list", False, Null) Then
    Return True
  Else
    Return False
  Endif

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Change or add a GlobalVar variable
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetGlobalVar(sVar As String, sValue As String, vValue As Variant, Optional sDataType As String = "")

  Dim cData As New JSONCollection

  cData.Add(sVar, "name")
  cData.Add(vValue, "value")
  If sDataType Then cData.Add(LCase(sDataType), "datatype")
  Call_JsonRpcClient("globalvar.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Delete a GlobalVar variable
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DelGlobalVar(sVar As String)

  Dim cData As New JSONCollection

  cData.Add(sVar, "name")
  Call_JsonRpcClient("globalvar.del", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Send an email
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendEmail(sTo As String, sSubject As String, sBody As String)

  Dim cData As New JSONCollection

  cData.Add(sBody, "msg")
  cData.Add(sSubject, "subject")
  cData.Add(sTo, "to")
  Call_JsonRpcClient("email.send", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Post a Tweet
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendTweet(sText As String)

  Dim cData As New JSONCollection

  cData.Add(sText, "msg")
  Call_JsonRpcClient("twitter.send", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Send a SMS
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendSMS(sTo As String, sText As String)

  Dim cData As New JSONCollection

  cData.Add(sTo, "to")
  cData.Add(sText, "msg")
  Call_JsonRpcClient("sms.send", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Set housemode
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetHouseMode(sMode As String)

  Dim cData As New JSONCollection

  cData.Add(sMode, "mode")
  Call_JsonRpcClient("housemode.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Set mute on/off
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetMuteMode(bMode As Boolean)

  Dim cData As New JSONCollection

  cData.Add(bMode, "mute")
  Call_JsonRpcClient("housemode.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Set the device state. On/Off/Dim xyz
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DeviceSetDevice(iDeviceId As Integer, sValue As String)

  Dim cData As New JSONCollection

  cData.Add(iDeviceId, "device_id")
  cData.Add(sValue, "value")
  Call_JsonRpcClient("device.set", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Update the ServerStats RRD Graph(s)
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateServerStatsGraphs(sRange As String)

  Dim cData As New JSONCollection

  cData.Add(sRange, "time")
  Call_JsonRpcClient("serverstat.update", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Create a RRD Graph(s) for a device
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CreateRRDs(iId As Integer)

  Dim cData As New JSONCollection

  cData.Add(iId, "device_id")
  Call_JsonRpcClient("rrdtool.create", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Update the RRD Graph(s)
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateRRDGraphs(sGroup As String, sRange As String)

  Dim cData As New JSONCollection

  cData.Add(sGroup, "group")
  cData.Add(sRange, "time")
  Call_JsonRpcClient("rrdtool.update", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Generate a RRD Graph
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GenerateRRDGraph(iGraph_id As Integer, sRange As String) As String

  Dim cData As New JSONCollection

  cData.Add(iGraph_id, "graph_id")
  cData.Add(sRange, "time")
  Return Call_JsonRpcClient("rrdtool.generate", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Delete one or all RRD File(s)
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DeleteRRD(iId As Integer)

  Dim cData As New JSONCollection

  cData.Add(iId, "device_id")
  Call_JsonRpcClient("rrdtool.deleterrd", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Sets the pin on a DSC security system
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmPin(sPin As String)

  Dim cData As New JSONCollection

  cData.Add(sPin, "pin")
  Call_JsonRpcClient("dsc.setpin", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Sets the alarm mode of a DSC security system
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmMode(sMode As String)

  Dim cData As New JSONCollection

  cData.Add(sMode, "mode")
  Call_JsonRpcClient("dsc.setalarm", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Plays the sound file, the file needs to be on the server
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PlaySound(sSound As String, iVolume As Integer)

  Dim cData As New JSONCollection

  cData.Add(sSound, "file")
  cData.Add(iVolume, "volume")
  Call_JsonRpcClient("sound.play", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Speak the text
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function VoiceTextSpeak(sText As String, sVoice As String)

  Dim cData As New JSONCollection

  cData.Add(sText, "text")
  cData.Add(sVoice, "voice")
  Call_JsonRpcClient("voicetext.speak", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Display the LEDMatrix message. iId=0-255 and the Message
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DisplayLEDMessage(iId As Integer, sText As String)

  Dim cData As New JSONCollection

  cData.Add(iId, "displayid")
  cData.Add(sText, "msg")
  Call_JsonRpcClient("ledmatrix.display", True, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVSetControl(sModel As String, sCmd As String, sValue As String, sAddress As String)

  Dim cData As New JSONCollection

  cData.Add(sModel, "model")
  cData.Add(sCmd, "cmd")
  cData.Add(sValue, "value")
  cData.Add(sAddress, "address")
  Call_JsonRpcClient("avcontrol.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVGetControl(sModel As String, sCmd As String, sAddress As String)

  Dim cData As New JSONCollection

  cData.Add(sModel, "model")
  cData.Add(sCmd, "cmd")
  cData.Add(sAddress, "address")
  Call_JsonRpcClient("avcontrol.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULSimulate(sPacket As String)

  Dim cData As New JSONCollection

  cData.Add(sPacket, "data")
  Call_JsonRpcClient("cul.simulate", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULQueueCommand(sPacket As String)

  Dim cData As New JSONCollection

  cData.Add(sPacket, "cmd")
  Call_JsonRpcClient("cul.queuecommand", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PLCBUSTXCommand(sAddress As String, sCmd As String, bAck As Boolean, bData As Byte)

  Dim cData As New JSONCollection

  cData.Add(sCmd, "cmd")
  cData.Add(sAddress, "address")
  cData.Add(bAck, "ack")
  cData.Add(bData, "data")
  Call_JsonRpcClient("cmdr.plcbus.txcommand", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Run event actions from the database
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunActions(iEventId As Integer)

  Dim cData As New JSONCollection

  cData.Add(iEventId, "event_id")
  Call_JsonRpcClient("event.run", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Run action from the database
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunAction(cData As JSONCollection) As Boolean

  Return Call_JsonRpcClient("action.run", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Run evaluation on the Server
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Condition_Eval(cData As JSONCollection) As String 

  Return Call_JsonRpcClient("condition.evaluate", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetPlanning()

  Call_JsonRpcClient("calendar.get", False, Null)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetPlanning()

  Dim d As Date
  Dim aStr As New String[]
  Dim cData As New JSONCollection

  For Each d In Calendar.dPlanning
    aStr.Add(d)
  Next

  cData.Add(aStr, "planning")
  Call_JsonRpcClient("calendar.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxSetVolumePlayer(sPlayerId As String, sVolume As String)

  Dim cData As New JSONCollection

  cData.Add("volume", "function")
  cData.Add(sPlayerId, "player")
  Try cData.Add(CInt(sVolume), "volume")
  If Error Then cData.Add(0, "volume")
  Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetVolumePlayer(sPlayerId As String) As String

  Dim cData As New JSONCollection

  cData.Add("volume", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxStopPlayer(sPlayerId As String)

  Dim cData As New JSONCollection

  cData.Add("stopplayer", "function")
  cData.Add(sPlayerId, "player")
  Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPlayPlayer(sPlayerId As String)

  Dim cData As New JSONCollection

  cData.Add("startplayer", "function")
  cData.Add(sPlayerId, "player")
  Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxNextNumberPlayer(sPlayerId As String)

  Dim cData As New JSONCollection

  cData.Add("nextnumber", "function")
  cData.Add(sPlayerId, "player")
  Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPrevNumberPlayer(sPlayerId As String)

  Dim cData As New JSONCollection

  cData.Add("prevnumber", "function")
  cData.Add(sPlayerId, "player")
  Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentTitlePlayer(sPlayerId As String) As String

  Dim cData As New JSONCollection

  cData.Add("currentnumber", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetModePlayer(sPlayerId As String) As String

  Dim cData As New JSONCollection

  cData.Add("mode", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerId(sPlayerIndex As String) As String

  Dim cData As New JSONCollection

  cData.Add("playerid", "function")
  cData.Add(sPlayerIndex, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerName(sPlayerIndex As String) As String

  Dim cData As New JSONCollection

  cData.Add("playername", "function")
  cData.Add(sPlayerIndex, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayer(sPlayerIndex As String) As String

  Dim cData As New JSONCollection

  cData.Add("playertype", "function")
  cData.Add(sPlayerIndex, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetAlbums() As String[]

  Dim cData As New JSONCollection

  cData.Add("albums", "function")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxClearPlaylistPlayer(sPlayerId As String) As Boolean

  Dim cData As New JSONCollection

  cData.Add("clearplaylist", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxAddAlbumToPlaylistPlayer(sPlayerId As String, sAlbumName As String) As Boolean

  Dim cData As New JSONCollection

  cData.Add("addalbumtoplaylist", "function")
  cData.Add(sPlayerId, "player")
  cData.Add(sAlbumName, "album")
  Return Call_JsonRpcClient("squeezebox.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentArtistPlayer(sPlayerId As String) As String

  Dim cData As New JSONCollection

  cData.Add("currentartist", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayerConnectedToServer(sPlayerId As String) As Boolean

  Dim cData As New JSONCollection

  cData.Add("isconnected", "function")
  cData.Add(sPlayerId, "player")
  Return Call_JsonRpcClient("squeezebox.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatDerogateHeating(iScenarioId As String, iHeatingId As String, sOperator As String) As Boolean

  Dim cData As New JSONCollection

  cData.Add(CInt(iScenarioId), "scenario_id")
  cData.Add(CInt(iHeatingId), "heating_id")
  cData.Add(sOperator, "operator")
  Return Call_JsonRpcClient("thermostat.derogateheating", False, cData)

Catch
  Return False

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatGetDerogateHeating(iHeatingId As String) As Float

  Dim cData As New JSONCollection

  cData.Add(CInt(iHeatingId), "heating_id")
  Return Call_JsonRpcClient("thermostat.getderogateheating", False, cData)

Catch
  Return 0.0

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tools: OpenZWave Commander Get
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ToolsOpenZWaveGet(sCommand As String, Optional iInstance As Integer = 0) As Variant

  Dim cData As New JSONCollection

  cData.Add(sCommand, "command")
  If iInstance <> 0 Then cData.Add(iInstance, "instance_id")

  Return Call_JsonRpcClient("tools.openzwave.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tools: OpenZWave Commander Set
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ToolsOpenZWaveSet(cData As JSONCollection) As Variant

  Return Call_JsonRpcClient("tools.openzwave.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tools: RFXCom Commander Get
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_RFXCom_Get(cData As JSONCollection) As Variant

  Return Call_JsonRpcClient("tools.rfxcom.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tools: RFXCom Commander Set
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_RFXCom_Set(cData As JSONCollection) As Variant

  Return Call_JsonRpcClient("tools.rfxcom.set", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tools: SerialPort Commander Get
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Tools_SerialPort_Get(cData As JSONCollection) As Variant

  Return Call_JsonRpcClient("tools.serialport.get", False, cData)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Weather information support
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Call_Weather_Get(cData As JSONCollection) As Variant

  Return Call_JsonRpcClient("weather.get", False, cData)

End
