' Gambas module file

' Description:
' JSONClient.module
' Support for client/server setup via JSON-RPC interface.

' Development Status:
' Working

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public LogLabel As String = "[JSONClient] "

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Get all global variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetGlobalVars()

  Dim cRpc As JsonRpcClient

  cRpc = New JsonRpcClient("globalvar.list") As "cRpcGlobalVars"
  cRpc.URL = "http://localhost:9090"
  cRpc.Call(Null)

Catch
  'Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'globalvar.get'")

End

