' Gambas module file

' Description:
' JSONClient.module
' Support for client/server setup via JSON-RPC interface.

' Development Status:
' Working

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public LogLabel As String = "[JSONClient] "

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetProgramVersion()

  Dim cRpc As JsonRpcClient
  Dim bOk As Boolean

  cRpc = New JsonRpcClient("domotiga.version") As "cRpcGetProgram"
  cRpc.URL = "http://localhost:9090"
  cRpc.Async = True
  bOk = cRpc.Call(Null)

  If Not bOk Then
    Main.WriteLog(LogLabel & "ERROR: Method: '" & cRpc.Method & "' returned '" & cRpc.ErrorMsg & "'")
    Return
  Endif

Catch
  Main.WriteLog(LogLabel & "ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "'. Method: '" & cRpc.Method & "'")

End

Public Sub cRpcGetProgram_Reply(vReply As Variant)

  FMain.CheckServerVersion(vReply)

End

Public Sub cRpcGetProgram_BadReply(sText As String)

  Main.WriteLog(LogLabel & "ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. Method: '" & Last.Method & "'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Get all global variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetGlobalVars()

  Dim cRpc As JsonRpcClient
  Dim cReply As Collection
  Dim bOk As Boolean

  cRpc = New JsonRpcClient("globalvar.list") As "cRpcGlobalVars"
  cRpc.URL = "http://localhost:9090"
  cRpc.Async = True
  bOk = cRpc.Call(Null)

  If bOk Then
    cReply = cRpc.Reply
  Else
    Print cRpc.ErrorMsg
    ' error
  Endif

Catch
  Main.WriteLog(LogLabel & "ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "'. Method: '" & cRpc.Method & "'")

End

Public Sub cRpcGlobalVars_Reply(vReply As Variant)

  Print "got replyyyyy"

End

Public Sub cRpcGlobalVars_BadReply(sText As String)

  'Main.WriteLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'system.program_version'.")

End
