' Gambas module file

' Description:
' NMA.module
' Contains code for sending NMA messages

' Development Status:
' Works.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Parse NMA XML Response
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Private Sub ParseNMAXML(sXML As String) As String[]

  Dim XmlR As New XmlReader
  Dim bNMA As Boolean
  Dim sOk As String
  Dim sCode As String
  Dim sRemaining As String
  Dim sResetDate As String
  Dim sErrorMessage As String
  Dim sPrevTag As String
  Dim aResponse As New String[5]

  ' aResponse[0] = success, error or unknown
  ' aResponse[1] = code
  ' aResponse[2] = remaining
  ' aResponse[3] = resetdate
  ' aResponse[4] = errormessage
  
  XmlR = New XmlReader
  Try XmlR.FromString(sXML)
  If Error Then
    aResponse[0] = "error"
    aResponse[4] = "Cannot parsing XML"
    Return aResponse
  Else
    ' First Node.Name = nma
    ' Second Node.Name = success or error

    Do While Not XmlR.Eof

      XmlR.Read()
      If XmlR.Node.Name = "nma" Then bNMA = True
      If bNMA Then
        If XmlR.Node.Name = "success" Or XmlR.Node.Name = "error" Then sOk = XmlR.Node.Name
      End If

      If sPrevTag = "error" And XmlR.Node.Name = "#text" Then sErrorMessage = XmlR.Node.Value
      sPrevTag = XmlR.Node.Name

      If XmlR.Node.Type = XmlReaderNodeType.Element Then
        If sOk Then
          If XmlR.Node.Attributes.count > 0 Then
            For Each XmlR.Node.Attributes
              If XmlR.Node.Name = "code" Then sCode = XmlR.Node.Value
              If XmlR.Node.Name = "remaining" Then sRemaining = XmlR.Node.Value
              If XmlR.Node.Name = "resetdate" Then sResetDate = XmlR.Node.Value
            Next
          End If
        End If
      End If
    Loop
  End If

  If sOk Then
    aResponse[0] = sOk
  Else
    aResponse[0] = "unknown"
  End If
  aResponse[1] = sCode
  aResponse[2] = sRemaining
  aResponse[3] = sResetDate
  aResponse[4] = sErrorMessage
  Return aResponse

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Validate NMA ApiKey
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub ValidateNMAApiKey(sApiKey As String) As String

  Dim hNMAValidate As HttpClient
  Dim sUrl As String = "https://www.notifymyandroid.com/publicapi/verify?"
  Dim sBuffer As String
  Dim aResponse As String[]

  If sApiKey = "" Then sApiKey = Main.sNMAApiKey
  sUrl &= "apikey=" & sApiKey

  hNMAValidate = New HttpClient As "hNMAValidate"
  hNMAValidate.URL = sUrl
  hNMAValidate.TimeOut = 3
  hNMAValidate.Async = False
  hNMAValidate.Get

  If hNMAValidate.Status < 0 Then
    ' Faillure fetching data or apikey is invalid
    If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Error validating API key=" & sApiKey & ", Code=" & hNMAValidate.Status & ", HttpCode=" & hNMAValidate.Code)
    Return "Failed, Code=" & hNMAValidate.Status & ", HTTP=" & hNMAValidate.code
  Else
    ' success or error - read the data
    If Lof(hNMAValidate) Then sBuffer = Read #hNMAValidate, Lof(hNMAValidate)

    aResponse = ParseNMAXML(sBuffer)
    Select Case aResponse[0]
      Case "success"
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Successfully validated API key=" & sApiKey & ", Code=" & aResponse[1] & ", Remaining=" & aResponse[2] & ", ResetDate=" & aResponse[3])
        Return ""
      Case "error"
        If aResponse[1] = "" Then aResponse[1] = hNMAValidate.Code
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Failed to validated API key= " & sApiKey & ", Code=" & aResponse[1] & ", ErrorMessage=" & aResponse[4])
        Return "Code=" & aResponse[1] & ", Msg=" & aResponse[4]
        Return False
      Default
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Unknown error validating API key=" & sApiKey & ", HttpCode=" & hNMAValidate.Code & ", XML=" & sBuffer)
        Return "Unknown XML, HTTP=" & hNMAValidate.Code
    End Select

  End If

  Return ""

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Post the NMA message
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub PostNMA(sApiKey As String, sApplication As String, sEvent As String, sDescription As String) As String

  Dim hNMAMessage As HttpClient
  Dim sUrl As String = "https://www.notifymyandroid.com/publicapi/notify?"
  Dim sBuffer As String
  Dim aResponse As String[]

  If sApiKey = "" Then sApiKey = Main.sNMAApiKey
  If sApplication = "" Then sApplication = Main.sNMAApplication
  If sEvent = "" Then sEvent = Main.sNMAEvent
  sUrl &= "apikey=" & sApiKey & "&" & "application=" & URL.Encode(sApplication) & "&" & "event=" & URL.Encode(sEvent) & "&" & "description=" & URL.Encode(sDescription)

  hNMAMessage = New HttpClient As "hNMAMessage"
  hNMAMessage.URL = sUrl
  hNMAMessage.TimeOut = 3
  hNMAMessage.Async = False
  hNMAMessage.Post("", "")

  If hNMAMessage.Status < 0 Then
    ' Faillure fetching data or apikey is invalid
    If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Error sending NMA message. API key=" & sApiKey & ", Code=" & hNMAMessage.Status & ", HttpCode=" & hNMAMessage.Code)
    Return "Failed, Code=" & hNMAMessage.Status & ", HTTP=" & hNMAMessage.Code
  Else
    ' success or error - read the data
    If Lof(hNMAMessage) Then sBuffer = Read #hNMAMessage, Lof(hNMAMessage)

    aResponse = ParseNMAXML(sBuffer)
    Select Case aResponse[0]
      Case "success"
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Successfully send message. API key=" & sApiKey & ", Code=" & aResponse[1] & ", Remaining=" & aResponse[2] & ", ResetDate=" & aResponse[3])
        Return ""
      Case "error"
        If aResponse[1] = "" Then aResponse[1] = hNMAMessage.Code
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Failed to send message. API key= " & sApiKey & ", Code=" & aResponse[1] & ", ErrorMessage=" & aResponse[4])
        Return "Code=" & aResponse[1] & ", Msg=" & aResponse[4]
      Default
        If Main.bNMADebug Then Main.WriteDebugLog("[NMA] Unknown error sending message. API key=" & sApiKey & ", HttpCode=" & hNMAMessage.Code & ", XML=" & sBuffer)
        Return "Unknown XML, HTTP=" & hNMAMessage.Code
    End Select

  End If

  Return ""
  
End
