' Gambas module file

' Description:
' P2000.module
' Monitor P2000 feed for ambulance, firebrigade dispatches near your location.

' Development Status:
' Just started.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Credits: Inspired by AZ_P2000.vb which was written by A.A. van Zoelen.

' Read file called COPYING for license details.

Public hP2000 As HttpClient
Public tP2000 As New Timer
Public sBuffer As String

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' start timer
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Run()

  Try tP2000.Stop

  ' create poll timer
  tP2000 = New Timer As "tP2000"
  tP2000.Delay = Main.iP2000Polltime * 1000
  tP2000.Start
  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Started poll timer."))

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' gets called at each timer event
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub tP2000_Timer()

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Updating data."))
  FetchFeedData()

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tries to fetch p2000 feed
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub FetchFeedData()

  Dim sURL As String = "http://feeds.livep2000.nl"

  ' if regio(s) set, add parameter to url
  If Main.sP2000Regios Then sURL = sURL & "?r=" & Main.sP2000Regios
  ' if discipline(s) set, add parameter to url
  If Main.sP2000Discipline Then sURL = sURL & IIf(Main.sP2000Regios, "&", "?") & "d=" & Main.sP2000Discipline

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Fetching data with request '") & sURL & "'")

  hP2000 = New HttpClient As "hP2000"
  hP2000.URL = sURL
  hP2000.Async = True
  hP2000.TimeOut = 5
  hP2000.Get

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get data
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hP2000_Read()

  If Lof(Last) Then sBuffer &= Read #Last, Lof(Last)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' parse data
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hP2000_Finished()

  Select Last.Code
    Case 200
      If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Received data '") & sBuffer & "'")
      ParseP2000data(sBuffer)
    Case Else
      If Main.bP2000Debug Then Main.WriteLog(("[P2000] Unknown error occured while trying to fetch P2000 feed data!"))
  End Select
  Last.Close

End

Private Sub ParseP2000data(sData As String) 

  Dim Xml As New XmlReader

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Processing XML data."))

  sBuffer = Replace(sData, "geo:lat", "geo_lat")
  sBuffer = Replace(sData, "geo:lon", "geo_lon")

  ' insert xml parse code here

  'http://whiteislandsoftware.com/forum/index.php?page=topicview&id=general%2Freading-xml-attributes
  'http://es.wikibooks.org/wiki/Gambas/Manipular_documentos_XML

End
