' Gambas module file

' Description:
' P2000.module
' Monitor P2000 feed for ambulance, firebrigade dispatches near your location.

' Development Status:
' Just started.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Credits: Inspired by AZ_P2000.vb which was written by A.A. van Zoelen.

' Read file called COPYING for license details.

Public hP2000 As HttpClient
Public tP2000 As New Timer
Public sBuffer As String

Public cTitle As New Collection
Public cLink As New Collection
Public cDescription As New Collection
Public cInfo As New Collection
Public cGeoLat As New Collection
Public cGeoLong As New Collection

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' start timer
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Run()

  Try tP2000.Stop

  ' create poll timer
  tP2000 = New Timer As "tP2000"
  tP2000.Delay = Main.iP2000Polltime * 1000
  tP2000.Start
  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Started poll timer."))

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' gets called at each timer event
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub tP2000_Timer()

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Updating data."))
  FetchFeedData()

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Tries to fetch p2000 data
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub FetchFeedData()

  Dim sURL As String = "http://feeds.livep2000.nl"

  ' if regio(s) set, add parameter to url
  ' 0 = All
  ' 1 = Groningen
  ' 2 = Friesland
  ' 3 = Drenthe
  ' 4 = IJsselland
  ' 5 = Twente
  ' 6 = Noord en Oost Gelderland
  ' 7 = Gelderland Midden
  ' 8 = Gelderland Zuid
  ' 9 = Utrecht
  ' 10 = Noord Holland Noord
  ' 11 = Zaanstreek-Waterland
  ' 12 = Kennemerland
  ' 13 = Amsterdam-Amstelland
  ' 14 = Gooi en Vechtstreek
  ' 15 = Haaglanden
  ' 16 = Hollands Midden
  ' 17 = Rotterdam Rijnmond
  ' 18 = Zuid Holland Zuid
  ' 19 = Zeeland
  ' 20 = Midden- en West-Brabant
  ' 21 = Brabant Noord
  ' 22 = Brabant Zuid en Oost
  ' 23 = Limburg Noord
  ' 24 = Limburg Zuid
  ' 25 = Flevoland

  If Len(Main.sP2000Regios) And If Main.sP2000Regios <> "0" Then sURL = sURL & "?r=" & Main.sP2000Regios

  ' if discipline(s) set, add parameter to url
  ' 0 = All
  ' 1 = Brandweer
  ' 2 = Ambulance
  ' 3 = Politie
  ' 4 = KNRM

  If Len(Main.sP2000Discipline) And If Main.sP2000Discipline <> "0" Then sURL = sURL & IIf(Main.sP2000Regios, "&", "?") & "d=" & Main.sP2000Discipline

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Fetching data with request '") & sURL & "'")

  hP2000 = New HttpClient As "hP2000"
  hP2000.URL = sURL
  hP2000.Async = True
  hP2000.TimeOut = 5
  hP2000.Get

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get data
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hP2000_Read()

  If Lof(Last) Then sBuffer &= Read #Last, Lof(Last)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' parse data
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hP2000_Finished()

  Select Last.Code
    Case 200
      ' too noisy
      ' If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Received data '") & sBuffer & "'")
      ParseP2000XML(sBuffer)
    Case Else
      If Main.bP2000Debug Then Main.WriteLog(("[P2000] Unknown error occured while trying to fetch P2000 feed data!"))
  End Select
  Last.Close
  sBuffer = Null

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' error raised
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hP2000_Error()

  If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Error fetching P200) feed: " & Last.Status)
  Try Last.Close

End

Private Sub ParseP2000data(sData As String) 

  If Main.bP2000Debug Then Main.WriteDebugLog(("[P2000] Processing XML data."))
  ParseP2000XML(sBuffer)

' For Each sBr In cInfo
'   Print cInfo.key & ": " & sBr
' Next
End

Private Function ParseP2000XML(sBuffer As String) As String

  Dim XmlR As New XmlReader
  Dim iMsg, iCnt As Integer
  Dim sFieldName, sFieldPos As String
  Dim sFieldHeader As New String[10]
  Dim bItem As Boolean

  ' empty collections first
  cTitle.Clear
  cLink.Clear
  cDescription.Clear
  cInfo.Clear
  cGeoLat.Clear
  cGeoLong.Clear

  XmlR.FromString(sBuffer)

  ' loop through the buffer
  While Not XmlR.Eof
    If XmlR.State = XmlReaderNodeType.Element Then sFieldHeader[XmlR.Node.depth] = XmlR.Node.name

    If CStr(XmlR.Node.Name) = "#text" Or If CStr(XmlR.Node.Name) = "#cdata" Then
      ' concat all headers to store position
      For iCnt = 0 To XmlR.Node.Depth - 1
        sFieldPos &= sFieldHeader[iCnt] & "|"
      Next

      ' found an item field, parse data
      If sFieldPos = "rss|channel|item|" Then 
        Select sFieldName
          Case "title"
            cTitle.Add(XmlR.Node.value, iMsg)
            If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Title: " & XmlR.Node.Value)
          Case "link"
            cLink.Add(XmlR.Node.value, iMsg)
             If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Link: " & XmlR.Node.Value)
          Case "br"
            If XmlR.Node.Value <> "]]>" Then
              If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Info: " & XmlR.Node.Value)
              If cInfo.Exist(iMsg) Then 
                cInfo[iMsg] &= XmlR.Node.Value
              Else
                cInfo.Add(XmlR.Node.value, iMsg)
              End If
            End If
          Case "geo:lat"
            cGeoLat.Add(XmlR.Node.value, iMsg)
            If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] GeoLat: " & XmlR.Node.Value)
          Case "geo:long"
            cGeoLong.Add(XmlR.Node.value, iMsg)
            If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] GeoLong: " & XmlR.Node.Value)

            ' if max number of messages is reached bail out
            If iMsg = Main.iP2000Messages - 1 Then Return

            ' if match text defined check if found in info text.
            If Len(Main.sP2000Filter) And If Not InStr(cTitle[iMsg], Main.sP2000Filter) Then
              If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Match text '" & Main.sP2000Filter & "' not found in '" & cTitle[iMsg] & "', skipping Message.")
              RemoveCollection(iMsg)
            End If

            Inc iMsg
          Case "description"
            cDescription.Add(XmlR.Node.value, iMsg)
            If Main.bP2000Debug Then Main.WriteDebugLog("[P2000] Description: " & XmlR.Node.Value)
        End Select
      Endif
      sFieldPos = ""
    Else
      sFieldName = XmlR.Node.Name
    End If
    XmlR.Read()
  Wend
  XmlR.Close

Catch
  Main.WriteDebugLog("ERROR: ParseP2000XML " & Error.Text & " at " & Error.Where)

End

Private Function RemoveCollection(sKey As String)

  ' remove collection
  cTitle.Remove(sKey)
  cLink.Remove(sKey)
  cDescription.Remove(sKey)
  cInfo.Remove(sKey)
  cGeoLat.Remove(sKey)
  cGeoLong.Remove(sKey)

End