' Gambas module file

' Description:
' Scenes.module
' This module provides support for scenes.

' Development Status:
' Just started

' Credits:
' Jesse Kerkhoven

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public LogLabel As String = "[Scene] "

Public Function Run(iSceneId As Integer) As Boolean
  
  Dim rResult As Result
  
  rResult = Main.hDB.Exec("SELECT * FROM scenes WHERE id = &1", iSceneId)
  If rResult.Count = 1 Then
    Events.RunActions(rResult!event_id)
    Return True
  Endif
  
  Main.WriteDebugLog(LogLabel & ("Error running scene with id '") & iSceneId & "'")
  Return False
  
End
