' Gambas module file

' Description:
' Twitter.module
' Support for sending tweets to twitter.com

' Development Status:
' Working.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

PUBLIC hTweet AS Process

PUBLIC SUB PostTweet(sMessage AS String) AS Boolean

  DIM sCmd AS String

  ' if not enabled, return
  IF NOT Main.bTwitterEnabled THEN
    IF Main.bTwitterDebug THEN Main.WriteDebugLog(("[Twitter] You want to send a tweet '") & sMessage & ("' but the interface is disabled!"))
    RETURN
  ENDIF

  IF Main.ProgramExist("bti") THEN
    IF Main.bTwitterTimeStamp THEN sMessage = Format$(Now(), "hh:nn:ss ") & sMessage
    sCmd = "echo '" & sMessage & "'|bti"
    IF Main.bTwitterDebug THEN Main.WriteDebugLog(("[Twitter] Running '") & sCmd & "'")
    hTweet = SHELL sCmd FOR READ AS "Tweet"
  ELSE
    Main.WriteDebugLog(("[Twitter] You need to install the oauth library and bti command to use Twitter!"))
    RETURN FALSE
  ENDIF

  RETURN TRUE

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get process return value, 0 means ok, anything else is an error
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Tweet_Kill()

  DIM iRc AS Integer

  iRc = LAST.Value
  IF iRc THEN
    Main.WriteDebugLog(("[Twitter] Error with return code ") & iRc)
  ELSE
    Main.WriteLog(("I have sent a Tweet to 'http://twitter.com/") & Main.sTwitterUser & "'.")
  ENDIF

END
