' Gambas module file

' Description:
' Util.module
' This module provides generic routines available in all other modules and classes, and not putting it in the Main.module anymore

' Development Status:
' Just started

' Credits:
' Alexander Kuiper

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

' Following collection stores already downloaded files, normally no need to re-download
Private $cDownloadedFiles As New Collection

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Converts empty string to Chr(1), because Gambas doesn't support "" strings in collections
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub JSON_AddEmpty(sValue As String) As String

  If sValue Then
    Return sValue
  Else
    Return Chr(1)
  Endif

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Converts Chr(1) to empty string, because Gambas doesn't support "" strings in collections
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub JSON_RemoveEmpty(sValue As String) As String

  If sValue = Chr(1) Then
    Return ""
  Else
    Return sValue
  Endif

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Convert Unix Epoch to readable format 
' UTC=True - then timezone info will be added
' Hex=True - we expect a length of 8 and in hex format
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub TimeSinceEpoch(sTime As String, Optional bUTC As Boolean = False, Optional bHex As Boolean = False) As String

  Dim gTime As Date

  If bHex Then
    If Len(sTime) <> 8 Then Return ""
  Endif

  ' calculate time since epoch
  If bHex Then
    gTime = DateAdd(Date(1970, 1, 1), gb.Second, Val("&H" & sTime & "&"))
  Else
    gTime = DateAdd(Date(1970, 1, 1), gb.Second, Val(sTime))
  Endif

  If bUTC Then
    gTime = DateAdd(gTime, gb.Second, CInt(Main.fAstroAutoTimezone * 3600))
  Endif

  Return Format$(gTime, "yyyy/mm/dd hh:nn:ss")

Catch ' some errors
  Main.WriteDebugLog("[Util] ERROR: TimeSinceEpoch Failed (" & sTime & "), " & Error.Text & " at " & Error.Where)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Retrieve a file from the internet, from the give URL.
' The file will be download in the TmpFile location and
' the temporary filename will be returned
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub DownloadFile(SUrl As String, Optional bReDownload As Boolean = False) As String

  Dim hHttpC As HttpClient
  Dim sBuffer As String
  Dim SFile As String

  ' If we already downloaded the file, don't download it again
  If Not bReDownload Then
    If $cDownloadedFiles.Exist(sUrl) Then
      Return $cDownloadedFiles[sUrl]
    Endif
  Endif

  hHttpC = New HttpClient
  hHttpC.URL = sUrl
  hHttpC.Async = False
  hHttpC.Timeout = 5
  hHttpC.Get()

  '--- check if succesfull ---
  If hHttpC.Status < 0 Then
    '--- something went wrong ---
    Main.WriteDebugLog("[Util] ERROR: Unable to download URL '" & sUrl & "' Code=" & CStr(hHttpC.Status))
    Return ""
  Else
    '--- success - read the data ---
    If Lof(hHttpC) Then sBuffer = Read #hHttpC, Lof(hHttpC)
  Endif

  '--- do a final check (especially for WeatherBug) ---
  If Trim(UCase(sBuffer)) = "ACCESS DENIED" Then
    Main.WriteDebugLog("[Util] ERROR: Access denied to URL '" & sUrl & "'")
    Return ""
  Else
    sFile = Temp() & "." & File.Ext(sUrl)
    File.Save(sFile, sBuffer)
    $cDownloadedFiles[sUrl] = sFile
    Return sFile
  Endif

End
