' Gambas module file

' Description:
' VideoServer.module
' Support getting captures from for Aviosys IP9100 Videoserver

' Development Status:
' Sort of working, needs better error checking.

' Links:
' http://www.sunspot.co.uk/Projects/IP_KAM_9000and9100_notes.htm

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.n

' Read file called COPYING for license details.

Private hDownloadImage As HttpClient
Private iCamera As Integer
Private sMessage As String
Private sToAddress As String
Private sSubject As String

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' grab image from channel #iCam and store it as a blob
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Grab(iCam As Integer, Optional sSubj As String, Optional sMsg As String, Optional sTo As String)

  Dim sTemp, sUrl As String

  iCamera = iCam
  If sMsg Then sMessage = sMsg
  If sTo Then sToAddress = sTo
  If sSubj Then sSubject = sSubj

  If Main.iVideoServerPort <> 0 And If Main.iVideoServerPort <> 80 Then sUrl &= ":" & Main.iVideoServerPort
  If Main.sVideoServerUser Then
    sTemp = Subst("&1:&2@&3", Main.sVideoServerUser, Main.sVideoServerPassword, Main.sVideoServerAddress)
  Else
    sTemp = Main.sVideoServerAddress
  Endif
  sUrl = "http://" & sTemp & "/usr/yoics" & iCam & ".jpg"
  If Main.bVideoServerDebug Then Main.WriteDebugLog(("[VideoServer] Fetching URL ") & sUrl)

  hDownloadImage = New HttpClient As "hDownloadImage"
  hDownloadImage.URL = sUrl
  hDownloadImage.TimeOut = 5
  hDownloadImage.Async = True
  hDownloadImage.Get()

End

Public Sub hDownloadImage_Finished()

  Dim iCount As Integer
  Dim sDownload As String

  Select hDownloadImage.Code
    Case 200
      Main.WriteLog(("I have captured an image from camera #") & iCamera & ".")
      If Lof(hDownloadImage) Then sDownload = Read #hDownloadImage, Lof(hDownloadImage)
      SaveCapture(sDownload, iCamera)
      If sSubject Then Mail.SendCaptureByMail(Application.Name & ": " & sSubject, sMessage, iCamera, sToAddress)
    Case 401
      Main.WriteLog(("Error authenticating while trying to capture a camera #") & iCamera & (" image!"))
    Case Else
      Main.WriteLog(("Unknown error occured while trying to capture a camera #") & iCamera & (" image!"))
  End Select

  If Not Main.bVideoServerDebug Then Return
  For iCount = 0 To hDownloadImage.Headers.Count - 1
    Main.WriteDebugLog("[VideoServer] " & hDownloadImage.Headers[iCount], 1)
  Next

End

Public Sub hDownloadImage_Error()

  Main.WriteDebugLog(("[VideoServer] Error ") & hDownloadImage.Status)

End

Public Sub SaveCapture(sBuffer As String, iCam As Integer)

  Dim rResult As Result

  ' write image to capture table
  Main.hDB.Begin()
  rResult = Main.hDB.Create("capture_camera" & iCam)
  rResult!image = sBuffer
  rResult!stamp = Now()
  rResult.Update()
  Main.hDB.Commit()

End
