' Gambas module file

' Description:
' XMLClient.module
' Support for client/server setup via XMLRPC interface.

' Development Status:
' Sort of working, needs better error checking.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' let server reload config and restart module named sModule
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ModuleRestart(sModule As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("module.restart", [XmlRpc.xstring], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcModuleRestart"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sModule)
  cRpc.Call(vVar)
  
Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'module.restart'.")

End

Public Sub cRpcModuleRestart_Reply(bOk As Variant)

  If bOk Then
    Main.WriteLog("Successfully (re)started module on server.")
  Else
    Main.WriteLog("[XMLClient] ERROR: There was a problem (re)starting module on server, check it's log.")
  Endif

End

Public Sub cRpcModuleRestart_BadReply(sText As String)

  Main.WriteLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'module.restart'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' send e-mail
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendEmail(sTo As String, sSubject As String, sBody As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("send.email", [XmlRpc.xString, XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSendEmail"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sTo)
  vVar.Add(sSubject)
  vVar.Add(sBody)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully sent e-mail to '" & sTo & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem sending e-mail to " & sTo & ".")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL 'http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort & "', XML-RPC method: 'send.email'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' send tweet
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendTweet(sText As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("send.tweet", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSendTweet"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sText)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully sent tweet to 'http://twitter.com/" & Main.sTwitterUser & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem sending tweet to 'http://twitter.com/" & Main.sTwitterUser & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL 'http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort & "', XML-RPC method: 'send.tweet'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' send sms
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SendSMS(sTo As String, sText As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("send.sms", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSendSMS"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sTo)
  vVar.Add(sText)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully sent SMS to '" & sTo & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem sending SMS to '" & sTo & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'send.sms'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set house mode
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetHouseMode(sMode As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("set.housemode", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSetHouseMode"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sMode)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set House mode to '" & sMode & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem setting House mode to '" & Main.Caps(sMode) & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'set.housemode'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set mute mode
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetMuteMode(bMode As Boolean)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("set.mutemode", [XmlRpc.xBoolean], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSetMudeMode"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(bMode)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set Mute mode to '" & IIf(bMode, "Audio Disabled", "Audio Enabled") & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem setting Mute mode to '" & bMode & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'set.mutemode'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set device value
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DeviceSetDevice(sDevice As String, sValue As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("device.setdevice", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSetDevice"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sDevice)
  vVar.Add(sValue)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'device.setdevice'.")

End

Public Sub cRpcSetDevice_Reply(bOk As Variant)

  If Not bOk Then Main.WriteLog("ERROR: There was a problem setting value of device!")

End

Public Sub cRpcSetDevice_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'device.setdevice'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' update serverstats graphs
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateServerStatsGraphs(sRange As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("serverstats.updategraphs", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcServerUpdateGraphs"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sRange)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'serverstats.updategraphs'.")

End

Public Sub cRpcServerUpdateGraphs_Reply(bOk As Variant)

  If Not bOk Then Main.WriteLog("ERROR: There was a problem updating serverstats graphs.")

End

Public Sub cRpcServerUpdateGraphs_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'serverstats.updategraphs'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' create rrdtool databases
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CreateRRDs(iId As Integer)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("rrdtool.createrrds", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcCreateRRDs"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(iId)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'rrdtool.createrrds'.")

End

Public Sub cRpcCreateRRDs_Reply(bOk As Variant)

  If Not bOk Then Main.WriteLog("ERROR: There was a problem creating rrdtool databases.")

End

Public Sub cRpcCreateRRDs_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'serverstats.updategraphs'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' update rrdtool graphs for a group and range
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function UpdateRRDGraphs(sGroup As String, sRange As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("rrdtool.updategraphs", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcUpdateRRDGraphs"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sGroup)
  vVar.Add(sRange)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'rrdtool.updategraphs'.")

End

Public Sub cRpcUpdateRRDGraphs_Reply(bOk As Variant)

  If Not bOk Then Main.WriteLog("ERROR: There was a problem updating rrdtool graphs.")

End

Public Sub cRpcUpdateRRDGraphs_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'rrdtool.updategraphs'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set alarm pin
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmPin(sPin As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("set.alarmpin", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSetAlarmPin"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPin)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'set.alarmpin'.")

End

Public Sub cRpcSetAlarmPin_Reply(bOk As Variant)

  If bOk Then
    Main.WriteLog("Successfully set Alarm pin.")
  Else
    Main.WriteLog("ERROR: There was a problem setting Alarm pin.")
  Endif

End

Public Sub cRpcSetAlarmPin_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'set.alarmpin'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set alarm mode
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetAlarmMode(sMode As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("set.alarmmode", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcSetAlarmMode"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sMode)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'set.alarmmode'.")

End

Public Sub cRpcSetAlarmMode_Reply(bOk As Variant)

  If bOk Then
    Main.WriteLog("Successfully set Alarm mode.")
  Else
    Main.WriteLog("ERROR: There was a problem setting Alarm mode.")
  Endif

End

Public Sub cRpcSetAlarmMode_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'set.alarmmode'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' play sound
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PlaySound(sSound As String, iVolume As Integer)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("play.sound", [XmlRpc.xString, XmlRpc.xInteger], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcPlaySound"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sSound)
  vVar.Add(iVolume)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'play.sound'.")

End

Public Sub cRpcPlaySound_Reply(bOk As Variant)

  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem playing sound.")
  Endif

End

Public Sub cRpcPlaySound_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'play.sound'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' speak voicetext
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function VoiceTextSpeak(sText As String, sVoice As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("voicetext.speak", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcVoiceTextSpeak"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sText)
  vVar.Add(sVoice)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'voicetext.speak'.")

End

Public Sub cRpcVoiceTextSpeak_Reply(bOk As Variant)

  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem speaking voicetext.")
  Endif

End

Public Sub cRpcVoiceTextSpeak_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'voicetext.speak'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' display led matrix message
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DisplayLEDMessage(sId As String, sText As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]

  fRpc = New RpcFunction("display.ledmessage", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc) As "cRpcDisplayLEDMesssage"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sId)
  vVar.Add(sText)
  cRpc.Call(vVar)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'display.ledmessage'.")

End

Public Sub cRpcDisplayLEDMesssage_Reply(bOk As Variant)

  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem displaying led message.")
  Endif

End

Public Sub cRpcDisplayLEDMesssage_BadReply(sText As String)

  Main.WriteDebugLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "'. XML-RPC method: 'display.ledmessage'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set audio control
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVSetControl(sModel As String, sCmd As String, sValue As String, sAddress As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("av.setcontrol", [XmlRpc.xString, XmlRpc.xString, XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sModel)
  vVar.Add(sCmd)
  vVar.Add(sValue)
  vVar.Add(sAddress)

  bOk = cRpc.Call(vVar)
  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem controlling audio/video device '" & sModel & "' with '" & sCmd & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'av.setcontrol'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get audio control
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function AVGetControl(sModel As String, sCmd As String, sAddress As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("av.getcontrol", [XmlRpc.xString, XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sModel)
  vVar.Add(sCmd)
  vVar.Add(sAddress)

  bOk = cRpc.Call(vVar)
  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem getting audio/video device setting '" & sModel & "' with '" & sCmd & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'av.getcontrol'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Get all global variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetGlobalVars()

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient

  fRpc = New RpcFunction("globalvar.get", Null, XmlRpc.xArray)
  cRpc = New RpcClient(fRpc) As "cRpcGlobalVars"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  cRpc.Call(Null)

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'globalvar.get'")

End

Public Sub cRpcGlobalVars_Reply(vReply As Variant)

  Dim vValue As Variant
  Dim sVar As String
  Dim i As Integer

  ' Clear the GlobalVar before we start filling it
  Main.ClearGlobalVars()

  For i = 0 To (vReply.Count - 1) / 2
    vValue = Main.HtmlDecode(vReply.Pop())
    sVar = Main.HtmlDecode(vReply.Pop())
    Main.SetGlobalVar(sVar, vValue)
  Next

Catch
  Main.WriteLog("[XMLClient] ERROR: " & Error.Text & " at " & Error.Where)

End

Public Sub cRpcGlobalVars_BadReply(sText As String)

  Main.WriteLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'globalvar.get'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set global variables
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetGlobalVar(sVar As String, sValue As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("globalvar.set", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(Main.HtmlEncode(sVar))
  vVar.Add(Main.HtmlEncode(sValue))

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set '" & sVar & "' to '" & sValue & "'.")
  Else
    Main.WriteLog("[XMLClient] ERROR: There was a problem setting '" & sVar & "' to '" & sValue & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'globalvar.set'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' save global var to database
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SaveGlobalVars()

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim bOk As Boolean

  fRpc = New RpcFunction("globalvar.save", Null, XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort

  cRpc.Call(Null)
  If bOk Then
    Main.WriteLog("Successfully saved globalvars to database.")
  Else
    Main.WriteLog("[XMLClient] ERROR: There was Saving global vars to database.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'globalvar.save'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' delete globalvar
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function DelGlobalVar(sVar As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("globalvar.del", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(Main.HtmlEncode(sVar))

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully deleted '" & sVar & "'.")
  Else
    Main.WriteLog("[XMLClient] ERROR: There was a problem deleting '" & sVar & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'globalvar.del'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' cul simulate packet
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULSimulate(sPacket As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("cmdr.culsimulate", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPacket)

  bOk = cRpc.Call(vVar)
  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem simulating CUL packet '" & sPacket & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'cmdr.culsimulate'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' cul queuecommand
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function CULQueueCommand(sPacket As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("cmdr.culqueuecommand", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPacket)

  bOk = cRpc.Call(vVar)
  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem queueing CUL command '" & sPacket & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'cmdr.culqueuecommand'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' plcbus send command
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function PLCBUSTXCommand(sAddress As String, sCmd As String, bAck As Boolean, bData As Byte)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("cmdr.plcbustxcommand", [XmlRpc.xString, XmlRpc.xString, XmlRpc.xBoolean, XmlRpc.xInteger], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sAddress)
  vVar.Add(sCmd)
  vVar.Add(bAck)
  vVar.Add(bData)

  bOk = cRpc.Call(vVar)
  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem sending PLCBUS command for '" & sAddress & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'cmdr.plcbustxcommand'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' run actions from event
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunActions(iEventId As Integer)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("events.runactions", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(Str(iEventId))

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully executed actions from event with id '" & iEventId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem executing actions from event with id '" & iEventId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'events.runactions'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' run action
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function RunAction(iActionId As Integer)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("events.runaction", [XmlRpc.xInteger], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(iActionId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully executed action with id '" & iActionId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem executing action with id '" & iActionId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: " & Error.Text & " when posting to URL '" & cRpc.URL & "', XML-RPC method: 'events.runaction'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get program version
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub GetProgramVersion() As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim sResult As String

  fRpc = New RpcFunction("system.program_version", Null, XmlRpc.xString)
  cRpc = New RpcClient(fRpc) As "cRpcGetProgram"
  cRpc.Mode = RpcClient.httpAsync
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  Try sResult = cRpc.Call(Null)

Catch
  Message("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'system.program_version'.")

End

Public Sub cRpcGetProgram_Reply(vReply As Variant)

  FMain.CheckServerVersion(vReply)

End

Public Sub cRpcGetProgram_BadReply(sText As String)

  Main.WriteLog("[XMLClient] ERROR: '" & sText & "' when posting to URL '" & Last.URL & "', XML-RPC method: 'system.program_version'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get calendar planning
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function GetPlanning()

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim Result As RpcArray
  Dim d As Date
  Dim i As Integer

  fRpc = New RpcFunction("calendar.getplanning", Null, XmlRpc.xArray)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  Result = cRpc.Call(Null)

  Calendar.dPlanning.Clear()
  For i = 0 To (Result.Count - 1)
    d = Result.Pop()
    Calendar.dPlanning.Add(d)
  Next

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'calendar.getplanning'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set planning
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SetPlanning()

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean
  Dim d As Date
  Dim list As New RpcArray

  fRpc = New RpcFunction("calendar.setplanning", [XmlRpc.xArray], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort

  For Each d In Calendar.dPlanning
    list.Add(d, XmlRpc.xDate)
  Next

  vVar.Add(list)

  bOk = cRpc.Call(vVar)

  If bOk Then
    Main.WriteLog("Successfully set occupancy planning.")
  Else
    Main.WriteLog("ERROR: There was a problem setting ocupancy planning.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'calendar.setplanning'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set volume squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxSetVolumePlayer(sPlayerId As String, sVolume As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.setvolumeplayer", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)
  vVar.Add(sVolume)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set volume player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to set volume player '" & sPlayerId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.setvolumeplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' play squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetVolumePlayer(sPlayerId As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getvolumeplayer", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMLClient] ERROR: " & Error.Text & " when posting to URL 'http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort & "'")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' stop squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxStopPlayer(sPlayerId As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.stopplayer", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set stop player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to set stop player '" & sPlayerId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.stopplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' play squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPlayPlayer(sPlayerId As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.playplayer", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set play player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to set play player '" & sPlayerId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.playplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set next number squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxNextNumberPlayer(sPlayerId As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.nextnumberplayer", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set next number player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to set next number player '" & sPlayerId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.nextnumberplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' set prev squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxPrevNumberPlayer(sPlayerId As String)

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.prevnumberplayer", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set prev number player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to set prev number player '" & sPlayerId & "'.")
  Endif

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.prevnumberplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current title squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentTitlePlayer(sPlayerId As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getcurrentnumberplayer", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getcurrentnumberplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current mode squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetModePlayer(sPlayerId As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getmodeplayer", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc) As "cRpcSqueezeboxGetModePlayer"
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)
  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getmodeplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current player id squeezebox player with player index
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerId(sPlayerIndex As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getplayerid", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerIndex)
  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getplayerid'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current name squeezebox player with player index
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetPlayerName(sPlayerIndex As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getplayername", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerIndex)
  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getplayername'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current type squeezebox player with player index
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayer(sPlayerIndex As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sResult As String

  fRpc = New RpcFunction("squeezebox.getisplayer", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerIndex)
  sResult = cRpc.Call(vVar)

Finally
  Return sResult

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getisplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get albums squeezebox server
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetAlbums() As String[]

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim sResult As New RpcArray
  Dim aResults As New String[]
  Dim i As Integer

  fRpc = New RpcFunction("squeezebox.getalbums", Null, XmlRpc.xArray)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  sResult = cRpc.Call(Null)

  For i = 0 To (sResult.Count - 1)
    aResults.Add(sResult.Pop())
  Next

Finally
  Return aResults

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getalbums'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' clear playlist squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxClearPlaylistPlayer(sPlayerId As String) As Boolean

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.clearplaylistplayer", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set clear playlist player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to clear playlistplayer '" & sPlayerId & "'.")
  Endif

Finally
  Return bOk

Catch
   Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.clearplaylistplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' add album to playlist squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxAddAlbumToPlaylistPlayer(sPlayerId As String, sAlbumName As String) As Boolean

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("squeezebox.addalbumtoplaylistplayer", [XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)
  vVar.Add(sAlbumName)

  bOk = cRpc.Call(vVar)
  If bOk Then
    Main.WriteLog("Successfully set add album to playlist player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to add a ablum to playlist player '" & sPlayerId & "'.")
  Endif

Finally
  Return bOk

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.addalbumtoplaylistplayer'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get current artist squeezebox player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetCurrentArtistPlayer(sPlayerId As String) As String

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim sArtist As String

  fRpc = New RpcFunction("squeezebox.getcurrentartistplayer", [XmlRpc.xString], XmlRpc.xString)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  sArtist = cRpc.Call(vVar)
  If sArtist = Not Null Then
    Main.WriteLog("Successfully get current artist player '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to get current artist player '" & sPlayerId & "'.")
  Endif

Finally
  Return sArtist

Catch
  Main.WriteLog("[XMLClient ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getcurrentartistplayer'")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' is player connected to squeezebox server player with player id
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function SqueezeboxGetIsPlayerConnectedToServer(sPlayerId As String) As Boolean

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bConnected As Boolean

  fRpc = New RpcFunction("squeezebox.getplayerisconnectedtoserver", [XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(sPlayerId)

  bConnected = cRpc.Call(vVar)
  If bConnected Then
    Main.WriteLog("Successfully player is connected to server player id '" & sPlayerId & "'.")
  Else
    Main.WriteLog("ERROR: There was a problem to get player is connected to server player id '" & sPlayerId & "'.")
  Endif

Finally
  Return bConnected

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'squeezebox.getplayerisconnectedtoserver'")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatDerogateHeating(iScenarioId As String, iHeatingId As String, sOperator As String) As Boolean

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim bOk As Boolean

  fRpc = New RpcFunction("thermostat.derogateheating", [XmlRpc.xString, XmlRpc.xString, XmlRpc.xString], XmlRpc.xBoolean)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(iScenarioId)
  vVar.Add(iHeatingId)
  vVar.Add(sOperator)
  bOk = cRpc.Call(vVar)

  If Not bOk Then
    Main.WriteLog("ERROR: There was a problem derogating heating.")
  Endif

Finally
  Return bOk

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'thermostat.derogateheating'.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ThermostatGetDerogateHeating(iHeatingId As String) As Float

  Dim fRpc As RpcFunction
  Dim cRpc As RpcClient
  Dim vVar As New Variant[]
  Dim fResult As Float

  fRpc = New RpcFunction("thermostat.getderogateheating", [XmlRpc.xString], XmlRpc.xDouble)
  cRpc = New RpcClient(fRpc)
  cRpc.URL = "http://" & Main.sXMLRPCHost & ":" & Main.iXMLRPCPort
  vVar.Add(iHeatingId)
  fResult = cRpc.Call(vVar)

Finally
  Return fResult

Catch
  Main.WriteLog("[XMLClient] ERROR: '" & Error.Text & "' when posting to URL '" & cRpc.URL & "', XML-RPC method: 'thermostat.getderogateheating'")

End
