' Gambas module file

' Description:
' CallerID.module
' Support for CallerID related functions.

' Development Status:
' Just started.

' DomotiGa - an open source home automation program.
' Copyright(C) 2009-2010 Ron Klinkien

' Read file called COPYING for license details.

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' return name of caller if known
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function ReturnCallerID(sPhoneNo As String) As String

  Dim rResult As Result
  Dim sName, sPhoneNoPrefix As String

  If Len(sPhoneNo) Then
    If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Searching contacts for number '") & sPhoneNo & "'.")
    sName = FindCallerNameContact(sPhoneNo)
    If sName = "" Then
      sPhoneNoPrefix = Main.sCallerIDNationalPrefix & Main.sCallerIDAreaCode & sPhoneNo
      If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Searching contacts for number '") & sPhoneNoPrefix & "'.")
      sName = FindCallerNameContact(sPhoneNoPrefix)
    End If
    If sName = "" Then
      If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Searching online for number '") & sPhoneNo & "'.")
      sName = FindCallerNameOnline(sPhoneNo)
    End If
    If sName = "" Then
      If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Searching contacts for number '") & sPhoneNoPrefix & "'.")
      sName = FindCallerNameOnline(sPhoneNoPrefix)
    End If
    If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Found name '") & sName & "'.")
    Return IIf(Len(sName), sName, ("Unknown"))
  Else
    If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] No number to look for! (Hidden)"))
    Return ("[Hidden Number]")
  End If

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' look through contact tables for caller name
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function FindCallerNameContact(sPhoneNo As String) As String

  Dim rResult As Result
  Dim sName As String

  rResult = Main.hDB.Exec("SELECT name, cidphone FROM contacts WHERE phoneno LIKE &1", "%" & sPhoneNo & "%")
  If rResult.Count Then
    If rResult!cidphone Then
      sName = rResult!cidphone
    Else
      sName = rResult!name
    End If
  End If
  rResult = Main.hDB.Exec("SELECT name cidmobile FROM contacts WHERE mobileno LIKE &1", "%" & sPhoneNo & "%")
  If rResult.Count Then
    If rResult!cidmobile Then
      sName = rResult!cidmobile
    Else
      sName = rResult!name
    End If
  End If

  Return sName

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' search online database for caller name
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function FindCallerNameOnline(sPhoneNo As String, Optional bUpdate As Boolean) As String

  Dim hCallerID As New HttpClient
  Dim sURL, sBuffer, sName As String
  Dim aScan, aLine As String[]
  Dim rResult As Result
  Dim iId As Integer

  sURL = "http://www.gevonden.cc/zoek1.php?sort=lastname&search=1&phonenumber=" & sPhoneNo & "&export=csv"
  If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Fetching URL '") & sURL & "'")
  hCallerID = New HttpClient As "CallerID"
  hCallerID.URL = sURL
  hCallerID.Async = False
  hCallerID.TimeOut = 3
  hCallerID.Get

  If hCallerID.Status < 0 Then
    ' site not reachable
    If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Error fething URL (") & hCallerID.Status & ")")
    Return ""
  Else
    ' success - read the data
    If Lof(hCallerID) Then Read #hCallerID, sBuffer, Lof(hCallerID)
    sBuffer = Mid(sBuffer, 1, Len(sBuffer) - 1)
    ' doesn't start with a ", data not found
    If Left(sBuffer, 1) <> Chr(34) Then
      If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Not found!"))
      Return ""
    End If

    If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Response '") & sBuffer & "'")

    aLine = Split(sBuffer, "\n")
    ' "NUMBER";SURNAME;FIRSTNAME;ADDRESS;ZIPCODE;CITY
    aScan = Scan(aLine[0], "*;*;*;*;*;*")
    If aScan.Count = 6 Then
      If Len(aScan[2]) > 0 Then
        sName = aScan[2] & " " & aScan[1]
      Else
        sName = aScan[1]
      End If

      ' update contact info
      If bUpdate Then
        Try rResult = Main.hDB.Exec("SELECT * FROM contacts WHERE phoneno LIKE &1", sPhoneNo)
        If rResult.Count Then
          Try rResult = Main.hDB.Exec("UPDATE contacts SET name = &2, address = &3, zipcode = &4, city = &5 WHERE id = &1", rResult!id, sName, aScan[3], aScan[4], aScan[5])
        Else
          ' add new contact record to database
          Main.hDB.Begin()
          rResult = Main.hDB.Create("contacts")
          rResult!name = sName
          rResult!address = aScan[3]
          rResult!zipcode = aScan[4]
          rResult!city = aScan[5]
          rResult!phoneno = sPhoneNo
          rResult.Update()
          Main.hDB.Commit()
          Return "Added record.\n\nName:\n" & sName & "\n\n" & "Address:\n" & aScan[3] & "\n" & aScan[4] & "\n" & aScan[5] & "\n\nNumber:\n" & sPhoneNo
        End If
        Return "Updated record.\n\nName:\n" & sName & "\n\n" & "Address:\n" & aScan[3] & "\n" & aScan[4] & "\n" & aScan[5] & "\n\nNumber:\n" & sPhoneNo
      End If

      If Not Main.bCallerIDAutoCreateContacts Then Return sName & (" from ") & aScan[5]

      ' add new contact record to database
      Main.hDB.Begin()
      rResult = Main.hDB.Create("contacts")
      rResult!name = sName
      rResult!address = aScan[3]
      rResult!zipcode = aScan[4]
      rResult!city = aScan[5]
      rResult!phoneno = sPhoneNo
      rResult!comments = ("Auto created contact with data found on 'www.gevonden.cc'")
      rResult.Update()
      Main.hDB.Commit()
      If Main.bCallerIDDebug Then Main.WriteDebugLog(("[CallerID] Auto created contact record for '") & sName & (" from ") & aScan[5] & "'")
      Return sName & (" from ") & aScan[5]
    End If

  Endif

End
