' Gambas module file

' Description:
' Twitter.module
' Support for sending tweets to twitter.com

' Development Status:
' Working.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2010 Ron Klinkien

' Read file called COPYING for license details.

Public hTweet As Process

Public Sub PostTweet(sMessage As String) As Boolean

  ' if not enabled, return
  If Not Main.bTwitterEnabled Then Return

  If Main.ProgramExist("bti") Then
    If Main.bTwitterTimeStamp Then sMessage = Format$(Now(), "hh:nn:ss ") & sMessage
    hTweet = Shell "echo '" & sMessage & "'|bti" For Read As "Tweet"
  Else
    Main.WriteLog(("You need to install the oauth library and bti cmd to use Twitter!"))
    Return False
  Endif

  Return True

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get process return value, 0 means ok, anything else is an error
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Tweet_Kill()

  Dim iRc As Integer

  iRc = Last.Value
  If iRc Then
    Main.WriteDebugLog(("[Twitter] Error return code is ") & iRc)
  Else
    Main.WriteLog(("I have sent a Tweet to 'http://twitter.com/") & Main.sTwitterUser & "'.")
  Endif

End
