' Gambas module file

' Description:
' AIBO.module
' Support for Sony AIBO ERS-7 monitor if he/she is awake or not, and give him commands via e-mail.

' Development Status:
' Detecting AIBO and setting device status accordingly works, giving it commands via e-mail needs to be tested.

' Links:
' http://www.aiai.ed.ac.uk/project/aibo/aibo-mail.html
' http://littlegreengecko.org/aibomailref_mind3.htm

' DomotiGa - an open source home automation program.
' Copyright(C) 2008 Ron Klinkien

' Read file called COPYING for license details.

PUBLIC tAIBO AS NEW Timer

PUBLIC SUB CheckAIBO()

  DIM rResult AS Result

  rResult = Main.hDB.Exec("SELECT * FROM devices WHERE enabled is TRUE")

  IF rResult.Available THEN
    IF rResult.Count >= 1 THEN
      FOR EACH rResult
        IF InStr(Devices.FindTypeForDevice(rResult!id), "AIBO")
          IF Main.bAIBODebug THEN Main.WriteDebugLog("[AIBO] checking AIBO named '" & rResult!name & "' with address http://" & rResult!address)
          Ping(rResult!id, rResult!address)
        END IF
      NEXT
    ELSE
      Main.WriteLog("AIBO: no AIBO(s) found in device table!")
    END IF
  END IF
END

PUBLIC SUB Run()

  ' start poll timer for AIBO
  tAIBO = NEW Timer AS "tAIBO"
  tAIBO.Delay = Main.iAIBOPollTime * 1000 ' multiply for seconds
  tAIBO.Start

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' try to get url to see if AIBO is awake or not
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PRIVATE FUNCTION Ping(iId AS Integer, sAddress AS String) AS Boolean

  DIM hAIBO AS NEW HttpClient
  DIM sStatus, sURL AS String

  sURL = "http://" & sAddress

  hAIBO = NEW HttpClient AS "AIBOPing"
  hAIBO.URL = sURL
  hAIBO.Async = FALSE
  hAIBO.TimeOut = 1
  hAIBO.Get

  IF hAIBO.Status < 0 THEN
    sStatus = "Sleeping"
    ' not reachable, he's asleep
  ELSE
    sStatus = "Awake"
    ' success, he/she is awake
  END IF

  ' find and update device
  IF Main.bAIBODebug THEN Main.WriteDebugLog("[AIBO] dog with id " & iId & " is " & sStatus)
  Devices.ValueUpdate(iId, sStatus, "", "", "")

CATCH ' some errors
  Main.WriteLog("AIBO Error: " & ERROR.Text & "")
  RETURN FALSE

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' generate e-mail with requested command to sent to AIBO
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC FUNCTION Command(sUser AS String, sCommand AS String) AS Boolean

  ' todo, need to implement user->email routine
  ' Mail.SendMail("AIBO MAIL", sAddress, sCommand)

END

PRIVATE SUB tAIBO_Timer()

  CheckAIBO()

END
