' Gambas module file

' Description:
' AVControl.module
' Support for control of audio and video devices.

' Development Status:
' Just started.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2010 Ron Klinkien

' Read file called COPYING for license details.

PUBLIC SUB Set(sModel AS String, sCmd AS String, sValue AS String, sAddress AS String) AS Boolean

  SELECT LCase(sModel)
    CASE "denon"
      IF Main.hDenon THEN Main.hDenon.SetCommand(sCmd, sValue, sAddress)
    CASE "onkyo"
      IF Main.hOnkyo THEN Main.hOnkyo.SetCommand(sCmd, sValue, sAddress)
    CASE "squeezeplayer"
      IF Main.hSqueezeServer THEN Main.hSqueezeServer.SetCommand(sCmd, sValue, sAddress)
  END SELECT

END

PUBLIC SUB Get(sModel AS String, sCmd AS String, sAddress AS String) AS Boolean

  SELECT LCase(sModel)
    CASE "denon"
      IF Main.hDenon THEN Main.hDenon.GetCommand(sCmd, sAddress)
    CASE "onkyo"
      IF Main.hOnkyo THEN Main.hOnkyo.GetCommand(sCmd, sAddress)
    CASE "squeezeplayer"
      IF Main.hSqueezeServer THEN Main.hSqueezeServer.GetCommand(sCmd, sAddress)
  END SELECT

END

