' Gambas module file

' Description:
' DNS.module
' Provide basic DNS and IP resolution

' Development Status:
' TODO: make async if possible

' DomotiGa - an open source home automation program.
' Copyright(C) 2008 Ron Klinkien

' Read file called LICENSE for license details.

PRIVATE hDNS AS DnsClient

PUBLIC SUB ResolveHost(sIP AS String) AS String

  ' create DNS handle
  hDNS = NEW DnsClient AS "DNS"
  hDNS.HostIP = sIP
  hDNS.GetHostName()

  RETURN hDNS.HostName

END

PUBLIC SUB ResolveIP(sHostname AS String) AS String

  ' create DNS handle
  hDNS = NEW DnsClient AS "DNS"
  hDNS.HostName = sHostname
  hDNS.GetHostIP()

  RETURN hDNS.HostIP

END
