' Gambas module file

' Description:
' Heyu.module
' Use Heyu 2.0 to control X10 devices.

' Development Status:
' Writing is working, maybe better error checking is needed.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2010 Ron Klinkien.

' Reading device status written by Renaud.

' Read file called COPYING for license details.

PRIVATE sOutput AS String
PRIVATE sMonitorBuffer AS String
PRIVATE pMonitor AS Process

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' send a command with heyu
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB SendCommand(sDevice AS String, sValue AS String)

  DIM sCommand AS String

  SELECT CASE LCase(sValue)
    CASE "on", "off"
      sCommand = Main.sHeyuCommand & " " & LCase(sValue) & " " & sDevice
      SHELL sCommand & " 2>&1" FOR READ AS "Heyu"
      IF Main.bHeyuDebug THEN Main.WriteDebugLog(("[Heyu] Run: ") & sCommand)
    CASE ELSE
      Main.WriteDebugLog(("[Heyu] Unsupported command ") & sValue)
  END SELECT

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' got output, save it
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Heyu_Read()

  DIM sLine AS String

  READ #LAST, sLine, -256
  sOutput &= sLine

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' digitemp has finished, process it's output
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Heyu_Kill()

  IF Main.bHeyuDebug THEN Main.WriteDebugLog(("[Heyu] Result: ") & sOutput)
  sOutput = NULL

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' start heyu monitor
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Monitor()

  DIM sCommand AS String[]

  sCommand = [Main.sHeyuCommand, "monitor", "2>&1"]
  pMonitor = EXEC sCommand FOR READ AS "HeyuMonitor"

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' read monitor output
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB HeyuMonitor_Read()

  DIM sLine AS String

  TRY READ #LAST, sLine, -256
  IF ERROR THEN Main.WriteDebugLog(("[Heyu] Error reading data from Monitor output-> ") & Error.Text)
  IF Len(sLine) > 0 THEN
    sMonitorBuffer &= sLine
    IF InStr(sMonitorBuffer, "func") > 0 THEN
      ParseMonitorMessage(sMonitorBuffer)
      sMonitorBuffer = NULL
    ENDIF
  ENDIF

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' parse monitor output
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PRIVATE SUB ParseMonitorMessage(sMessage AS String)

  DIM iDeviceId AS Integer
  DIM aFirstLine, aSecondLine AS String[]
  DIM sAddress, sOrder AS String

  IF Main.bHeyuDebug THEN Main.WriteDebugLog(("[Heyu] Monitor get: ") & sMessage)  

  ' Message sample :
  ' 1 line : 09/19 18:44:53  rcvi addr unit       4 : hu I4  (_no_alias_)
  ' 2 line : 09/19 18:44:53  rcvi func          Off : hc I

  aFirstLine = Scan(sMessage, "*addr unit* : hu*(*")
  aSecondLine = Scan(sMessage, "*func*: hc*")

  IF aFirstLine.Count = 4 AND aSecondLine.Count = 3 THEN
    sAddress = Trim(aFirstLine[2])
    IF Len(sAddress) = 2 THEN
      sAddress = Left(sAddress, 1) & "0" & Right(sAddress, 1)
    ENDIF
    sOrder = Trim(aSecondLine[1])
    IF Main.bHeyuGlobalX10 THEN
      iDeviceId = Devices.Find(sAddress, 1024, "X10")
    ELSE
      iDeviceId = Devices.Find(sAddress, Devices.FindInterface("Heyu X10"), "X10")
    ENDIF
    ' if found then update it's value
    IF iDeviceId THEN
      Devices.ValueUpdate(iDeviceId, sOrder, "", "", "")
    ENDIF
  ENDIF

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' stop monitor
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Monitor_Stop()

  pMonitor.Kill

END
