' Gambas module file

' Description:
' Heyu.module
' Use Heyu 2.0 to control X10 devices.

' Development Status:
' Writing is working, maybe better error checking is needed.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2010 Ron Klinkien

' Read file called COPYING for license details.

PRIVATE sOutput AS String

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' send a command with heyu
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB SendCommand(sDevice AS String, sValue AS String)

  DIM sCommand AS String

  SELECT CASE LCase(sValue)
    CASE "on", "off"
      sCommand = Main.sHeyuCommand & " " & LCase(sValue) & " " & sDevice
      SHELL sCommand & " 2>&1" FOR READ AS "Heyu"
      IF Main.bHeyuDebug THEN Main.WriteDebugLog(("[Heyu] Run: ") & sCommand)
    CASE ELSE
      Main.WriteDebugLog(("[Heyu] Unsupported command ") & sValue)
  END SELECT

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' got output, save it
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Heyu_Read()

  DIM sLine AS String

  READ #LAST, sLine, -256
  sOutput &= sLine

END
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' digitemp has finished, process it's output
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Heyu_Kill()

  IF Main.bHeyuDebug THEN Main.WriteDebugLog(("[Heyu] Result: ") & sOutput)
  sOutput = NULL

END
