' Gambas module file

' Description:
' Heyu.module
' Use Heyu 2.0 to control X10 devices.

' Development Status:
' Writing is working, maybe better error checking is needed.

' DomotiGa - an open source home automation program.
' Copyright(C) 2008 Ron Klinkien

' Read file called LICENSE for license details.

PUBLIC SUB SendCommand(sDevice AS String, sValue AS String)

  SELECT CASE LCase(sValue)
    CASE "on", "off"
      EXEC [Main.sHeyuCommand, LCase(sValue) & " " & sDevice]
      IF Main.bHeyuDebug THEN Main.WriteDebugLog("[Heyu] " & Main.sHeyuCommand, LCase(sValue) & " " & sDevice)
    CASE ELSE
      Main.WriteDebugLog("[Heyu] Unsupported command " & sValue)
  END SELECT

END
