' Gambas module file

' Description:
' AVControl.module
' Support for control of audio and video devices.

' Development Status:
' Just started.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public sDenonCmds As String[] = ["power", "mainpower", "z2power", "volume", "z2volume", "mute", "z2mute", "input", "z2input", "cli"]
Public sDenonValues As String[] = ["on,off", "on,off", "on,off", "<db>,up,down,off", "<db>,up,down,off", "on,off", "on,off", "phone,cd,tuner,dvd,vdp,tv,dbs,vcr-1,vcr-2,vcr-3,v.aux,cdr/tape", "phone,cd,tuner,dvd,vdp,tv,dbs,vcr-1,vcr-2,vcr-3,v.aux", "<cmd>"]
Public sDenonInfo As String[] = ["Switch receiver power on/off", "Switch main zone power on/off", "Switch zone2 power on/off", "Set main volume", "Mute audio", "Mute audio zone2", "Select input source", "Select input source zone2", "Send a custom command"]

Public sOnkyoCmds As String[] = ["power", "z2power", "volume", "z2volume", "mute", "z2mute", "input", "z2input", "cli"]
Public sOnkyoValues As String[] = ["on,off", "on,off", "<0-100>,up,down,up1,down1", "<0-100>,up,down,up1,down1", "on,off,toggle", "on,off,toggle",
"vcr,dvr,video1,cbl/sat,video2,game/tv,game,video3,aux1,aux,video4,aux2,video5,video6,video7,dvd,tv/tape,tape,tape1,tape2,phono,cd,fm,am,tuner,net,server,inet radio,usb front,usb rear,port,up,down,off",
"vcr,dvr,video1,cbl/sat,video2,game/tv,game,video3,aux1,aux,video4,aux2,video5,video6,video7,dvd,tv/tape,tape,tape1,tape2,phono,cd,fm,am,tuner,net,server,inet radio,usb front,usb rear,port,up,down,off", "<cmd>"]
Public sOnkyoInfo As String[] = ["Switch receiver power on/off", "Switch zone2 power on/off", "Set main volume", "Set zone2 volume", "Mute audio", "Mute zone2 audio", "Select input source", "Select zone2 input", "Send a custom command"]

Public sIPortCmds As String[] = ["playctrl", "requestipodname", "leddocked", "ledundocked", "requestplayingsongindex"]
Public sIPortValues As String[] = ["play,next,stop,prev,startff,startrew,endffrew", "", "on,off,dim,medium,bright", "on,off,dim,medium,bright", ""]
Public sIPortInfo As String[] = ["Control play mode", "Request iPod name", "Control LED docked", "Control LED undocked", "Request playing song index"]

Public sSqueezeServerCmds As String[]
Public sSqueezeServerValues As String[]
Public sSqueezeServerInfo As String[]

Public sSharpTVCmds As String[] = ["power", "volume", "mute", "avmode", "wide", "tvchannel", "dtvchannel", "input", "surround", "text", "cli"]
Public sSharpTVValues As String[] = ["on,off", "0-60", "on,off", "1-7,100", "1-11", "1-99,up,down", "1-9999,up,down", "1-9,tv,dtv", "on,off", "on,off,100-899", ""]
Public sSharpTVInfo As String[] = ["Switch TV power on/off", "Set audio volume", "Mute audio", "Set av mode", "Set aspect ratio", "Select tv channel", "Select dtv channel", "Select input", "Set surround mode", "Control teletext", "Send custom command"]

Public sLGTVCmds As String[] = ["power", "volume", "mute", "screenmute", "aspect", "tvchannel", "cli"]
Public sLGTVValues As String[] = ["on,off", "0-100", "on,off", "on,off", "4:3,16:9", "back", ""]
Public sLGTVInfo As String[] = ["Switch TV power on/off", "Set audio volume", "Mute audio", "Mute screen", "Set aspect ratio", "Select channel", "Send a custom command"]

Public sPioneerCmds As String[] = ["power", "power_2", "volume", "volume_2", "mute", "mute_2", "input", "input_2", "cli"]
Public sPioneerValues As String[] = ["on,off", "on,off", "<db>,up,down,off", "<db>,up,down,off", "on,off", "on,off", "PHONO,CD,TUNER,CD-R/TAPE,DVD,TV/SAT,VIDEO1,VIDEO2,DVR/BDR,IPOD/USB,XMRadio,HDMI1,HDMI2,HDMI3,HDMI4,HDMI5,BD,HomeMedia,SIRIUS", "CD,TUNER,CD-R/TAPE,DVD,TV/SAT,VIDEO1,VIDEO2,DVR/BDR,IPOD/USB,XMRadio,BD,HomeMedia,SIRIUS", "<cmd>"]
Public sPioneerInfo As String[] = ["Switch receiver power on/off", "Switch zone 2 power on/off", "Set main volume", "Set zone 2 volume", "Mute audio", "Mute zone 2 audio", "Select input source", "Select input source zone 2", "Send a custom command"]


Public Sub Set(sModel As String, sCmd As String, sValue As String, sAddress As String) As Boolean

  Select LCase(sModel)
    Case "denon"
      Try Plugin.GetPluginObject("Denon", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
    Case "onkyo"
      Try Plugin.GetPluginObject("Onkyo", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
    Case "squeezeplayer"
      If Main.hSqueezeServer Then
        Main.hSqueezeServer.SetCommand(sCmd, sValue, sAddress)
        Return True
      Endif
    Case "iport"
      Try Plugin.GetPluginObject("IPort", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
    Case "lgtv"
      Try Plugin.GetPluginObject("LGTV", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
    Case "sharptv"
      Try Plugin.GetPluginObject("SharpTV", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
    Case "pioneer"
      Try Plugin.GetPluginObject("Pioneer", 1).Interface.SetCommand(sCmd, sValue, sAddress)
      If Not Error Then Return True
  End Select

  Return False

End

Public Sub Get(sModel As String, sCmd As String, sAddress As String) As Boolean

  Select LCase(sModel)
    Case "denon"
      Try Plugin.GetPluginObject("Denon", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
    Case "onkyo"
      Try Plugin.GetPluginObject("Onkyo", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
    Case "squeezeplayer"
      If Main.hSqueezeServer Then
        Main.hSqueezeServer.GetCommand(sCmd, sAddress)
        Return True
      Endif
    Case "iport"
      Try Plugin.GetPluginObject("IPort", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
    Case "lgtv"
      Try Plugin.GetPluginObject("LGTV", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
    Case "sharptv"
      Try Plugin.GetPluginObject("SharpTV", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
    Case "pioneer"
      Try Plugin.GetPluginObject("Pioneer", 1).Interface.GetCommand(sCmd, sAddress)
      If Not Error Then Return True
  End Select

  Return False

End
