' Gambas module file

' Description:
' Bwired.module
' Support for Bwired related functions.

' Development Status:
' Just build, so possible bugs around.

' Links:
' http://www.bwired.nl/domoticaworld.asp

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public hPost As New HttpClient As "hPost"
Public tBwired As Timer

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' start timer
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Run()

  ' start poll timer for Bwired
  tBwired = New Timer As "tBwired"
  tBwired.Delay = Main.iBwiredMapPushTime * 1000 * 60 ' multiply for minutes
  tBwired.Start

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' gets called at each timer event
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub tBwired_Timer()

  UploadBwiredData()

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' create xml data and upload it to the service
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub UploadBwiredData()

  Dim sContent As String

  ' if we are already uploading return
  If hPost.Status > 0 Then
    Main.WriteLog(("I'm already uploading sensor data to Bwired, skipping."))
    Return
  Endif

  ' create xml string
  sContent = CreateBwiredData()

  ' use httpclient to post xml to service
  hPost.URL = "http://www.bwired.nl/Bwiredservice/receive.asp"
  hPost.TimeOut = 10
  hPost.Async = True
  hPost.Post("text/xml", sContent)

  If Main.bBwiredMapDebug Then Main.WriteDebugLog("[Bwired] " & sContent)

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' scan bwired devices table and create xml document
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Private Function CreateBwiredData() As String

  Dim xXml As XmlWriter
  Dim sValue As String
  Dim rResult As Result
  Dim iId As Integer

  ' scan device table
  rResult = Main.hDB.Exec("SELECT * FROM devices_bwired")
  If Not rResult Then
    Main.WriteLog(("Error: table 'devices_bwired' not found!"))
    Return
  Endif

  ' build header
  xXml = New XmlWriter
  xXml.Open("", True, "UTF-8")
  xXml.StartElement("BWired")
  xXml.StartElement("Init")
    xXml.Element("DateTime", Now())
    xXml.Element("UserName", Main.sBwiredMapUser)
    xXml.Element("Password", Main.sBwiredMapPassword)
    xXml.Element("ScreenName", Main.sBwiredMapScreenName)
    xXml.Element("Gpslat", Main.sBwiredMapGpsLat)
    xXml.Element("Gpslong", Main.sBwiredMapGpsLong)
    xXml.Element("City", Main.sBwiredMapCity)
    xXml.Element("Website", Main.sBwiredMapWebsite)
    xXml.Element("WebCamPicUrl", Main.sBwiredMapWebsitePicUrl)
    xXml.Element("Title", Main.sBwiredMapTitle)
  xXml.EndElement()

  ' create device entries
  If rResult.Count Then
    For Each rResult
      xXml.StartElement("Entry")
      xXml.Element("Name", rResult!description)
      xXml.Element("ID", iId)
      xXml.Element("Units", rResult!devicelabel)
      sValue = Devices.GetCurrentValueForDevice(rResult!deviceid, rResult!value)
      xXml.Element("Value", sValue)
      xXml.EndElement()
      Inc iId
    Next
  Endif

  ' close document
  xXml.EndElement()
  Return xXml.EndDocument()

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' catch error
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hPost_Error()

  Main.WriteDebugLog(("[Bwired] Sensor data post error."))

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' check http return code
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub hPost_Finished()

  Dim iCount As Integer

  ' select on http result code and display message
  Select hPost.Code
    ' do a little magic as microsoft webserver's are strange
    Case 0
      If InStr(hPost.Headers[0], "HTTP/1.1 200") Or If InStr(hPost.Headers[0], "HTTP/1.1 100") Then
        Main.WriteLog(("Uploaded sensor data to Bwired."))
      Else
        Main.WriteLog(("Unknown error occured while uploading XML data to Bwired!"))
      Endif
    Case 401
      Main.WriteLog(("Error authenticating while uploading XML data to Bwired!"))
    Case 404
      Main.WriteLog(("Error page not found while uploading XML data to Bwired!"))
    Case Else
      Main.WriteLog(("Unknown error code (" & hPost.Code & ") returned after uploading XML data to Bwired!"))
  End Select

  ' if debug is on print all http headers
  If Not Main.bBwiredMapDebug Then Return
  For iCount = 0 To hPost.Headers.Count - 1
    Main.WriteDebugLog("[Bwired] " & Left(hPost.Headers[iCount], Len(hPost.Headers[iCount])))
  Next

End
