' Gambas module file

' Description:
' DNS.module
' Provide basic DNS and IP resolution

' Development Status:
' TODO: make async if possible

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2009 Ron Klinkien

' Read file called COPYING for license details.

PRIVATE hDNS AS DnsClient

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get hostname name that belongs to ip address
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB ResolveHost(sIP AS String) AS String

  ' create DNS handle
  hDNS = NEW DnsClient AS "DNS"
  hDNS.HostIP = sIP
  hDNS.Async = TRUE
  hDNS.GetHostName()

  RETURN hDNS.HostName

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get ip address that belongs to host name
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB ResolveIP(sHostname AS String) AS String

  ' create DNS handle
  hDNS = NEW DnsClient AS "DNS"
  hDNS.HostName = sHostname
  hDNS.Async = TRUE
  hDNS.GetHostIP()

  RETURN hDNS.HostIP

END
