' Gambas module file

' Description:
' DNS.module
' Provide basic DNS and IP resolution

' Development Status:
' TODO: make async if possible

' DomotiGa - an open source home automation program.
' Copyright(C) 2008-2009 Ron Klinkien

' Read file called COPYING for license details.

Private hDNS As DnsClient

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get hostname name that belongs to ip address
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub ResolveHost(sIP As String) As String

  ' create DNS handle
  hDNS = New DnsClient As "DNS"
  hDNS.HostIP = sIP
  ' hDNS.Async = TRUE
  hDNS.GetHostName()

  Return hDNS.HostName

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get ip address that belongs to host name
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub ResolveIP(sHostname As String) As String

  ' create DNS handle
  hDNS = New DnsClient As "DNS"
  hDNS.HostName = sHostname
  ' hDNS.Async = TRUE
  hDNS.GetHostIP()

  Return hDNS.HostIP

End
