' Gambas module file

' Description:
' Scenes.module
' This module provides support for scenes.

' Development Status:
' Just started

' Credits:
' Jesse Kerkhoven

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public LogLabel As String = "[Scene] "

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Run Scene
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Run(iSceneId As Integer) As Boolean
  
  Dim sTimeNow As String = Format(Now(), "yyyy-mm-dd hh:nn:ss")
  Dim rResult As Result
  
  rResult = Main.hDB.Exec("SELECT * FROM scenes WHERE scene_id=&1", iSceneId)
  If rResult.Count = 1 Then
    If rResult!enabled Then
      Events.RunActions(rResult!event_id)
      If rResult!firstrun = "00:00:00" Or If rResult!firstrun = "" Then
        rResult = Main.hDB.Exec("UPDATE scenes SET firstrun=&1, lastrun=&2 WHERE scene_id=&3", sTimeNow, sTimeNow, iSceneId)
      Else
        rResult = Main.hDB.Exec("UPDATE scenes SET lastrun=&1 WHERE scene_id=&2", sTimeNow, iSceneId)
      Endif
      Return True
    Else
      Return False
    Endif
  Endif
  
  Main.WriteDebugLog(LogLabel & "ERROR: running scene with id '" & iSceneId & "'")
  Return False
  
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Retrieve all scenes
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub GetScenesList(Optional cData As Collection) As Result

  Dim sWhere As String
  Dim rScene As Result

  If cData And If cData.Exist("scene_id") Then
    sWhere = "WHERE scene_id=" & cData.Exist("scene_id")
  Endif

  Try rScene = Main.hDB.Exec("SELECT * FROM scenes " & sWhere)
  If Error Then
    Main.WriteDebugLog(LogLabel & "ERROR: '" & Error.Text & "' at " & Error.Where)
  Endif

  Return rScene

End

