' Gambas module file

' Description:
' Scenes.module
' This module provides support for scenes.

' Development Status:
' Just started

' Credits:
' Jesse Kerkhoven

' Changes
' 19-May-2015 Max Lie added Scene create and delete function

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public LogLabel As String = "[Scene] "

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Run Scene
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Function Run(iSceneId As Integer) As Boolean
  
  Dim sTimeNow As String = Format(Now(), "yyyy-mm-dd hh:nn:ss")
  Dim rResult As Result
  
  rResult = Main.hDB.Exec("SELECT * FROM scenes WHERE id=&1", iSceneId)
  If rResult.Count = 1 Then
    If rResult!enabled Then
      Events.RunActions(rResult!event_id)
      If rResult!firstrun = "00:00:00" Or If rResult!firstrun = "" Then
        rResult = Main.hDB.Exec("UPDATE scenes SET firstrun=&1, lastrun=&2 WHERE id=&3", sTimeNow, sTimeNow, iSceneId)
      Else
        rResult = Main.hDB.Exec("UPDATE scenes SET lastrun=&1 WHERE id=&2", sTimeNow, iSceneId)
      Endif
      Return True
    Else
      Return False
    Endif
  Endif
  
  Main.WriteDebugLog(LogLabel & "ERROR: running scene with id '" & iSceneId & "'")
  Return False
  
End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Retrieve all scenes
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub GetScenesList(Optional cData As Collection) As Result

  Dim sWhere As String
  Dim rScene As Result

  If cData And If cData.Exist("scene_id") Then
    sWhere = "WHERE id=" & cData.Exist("scene_id")
  Endif

  Try rScene = Main.hDB.Exec("SELECT * FROM scenes " & sWhere)
  If Error Then
    Main.WriteDebugLog(LogLabel & "ERROR: '" & Error.Text & "' at '" & Error.Where & "'")
  Endif

  Return rScene

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' create Scene
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub createScene(iName As String, iEventId As Integer) As Boolean

  Dim rResult As Result

  rResult = Main.hDB.Exec("INSERT INTO scenes (enabled, name, event_id) VALUES(&1,&2,&3)", 1, iName, iEventId)

  If rResult.Count Then
    Return True
  Else
    Return False
  Endif

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' delete Scene
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub deleteScene(iId As Integer) As Boolean

  Dim rResult As Result


  rResult = Main.hDB.Exec("DELETE FROM scenes WHERE id = &1", iId)


  If rResult.Count Then
    Return True
  Else
    Return False
  Endif

End



