' Gambas module file

' Description:
' Sounds.module
' Play sound files on events.

' Development Status:
' Working.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Private sDefaultSoundDirectory As String

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' just a function to list available sounds
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub LoadSounds()

  Dim sSound As String
  Dim sSoundFiles As String[]

  sDefaultSoundDirectory = Main.sBaseDir &/ "sounds"

  ' fill array with available sounds
  sSoundFiles = Dir(sDefaultSoundDirectory, "*.wav")
  sSoundFiles.Insert(Dir(sDefaultSoundDirectory, "*.mp3"))
  sSoundFiles.Insert(Dir(sDefaultSoundDirectory, "*.ogg"))

  If Main.bSoundDebug Then
    For Each sSound In sSoundFiles
      Main.WriteDebugLog("[Sound] Found " & sSound)
    Next
  End If
  Main.WriteLog(sSoundFiles.Count & If(sSoundFiles.Count <> 1, " soundfiles", " soundfile") & " found.")

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' play sound with selected volume
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub PlaySnd(sFile As String, Optional iVol As Integer)

  Dim iVolume As Float
  Dim sSnd As String

  ' sound not enabled, return
  If Not Main.bSoundEnabled Then Return

  sSnd = sDefaultSoundDirectory &/ sFile

  If ivol Then ' custom volume
    iVolume = iVol
  Else ' default volume
    iVolume = Main.iSoundVolume
  Endif

  If Exist(sSnd) Then
    If Not Error Then
      Shell "amixer -q sset Master playback " & iVolume & "%" Wait
      If Not Main.GlobalVar["Mute"] Then
        Shell "aplay -q " & sSnd
        If Error Then
          Main.WriteDebugLog(("[Sound] Error playing soundfile ") & sSnd)
        Else
          Main.WriteLog("Playing sound " & sFile & ".")
          If Main.bSoundDebug Then Main.WriteDebugLog(("[Sound] Playing sound ") & sSnd & (" at volume ") & iVolume)
        End If
      Else
        Main.WriteLog(("[Muted] Playing sound ") & sFile & ".")
      End If
    Else
      Main.WriteDebugLog("[Sound] " & ERROR.text & " " & sSnd)
    End If
  Else
    Main.WriteDebugLog(("[Sound] The soundfile ") & sSnd & (" doesn't exist!"))
  End If

End
