' Gambas module file

' Description:
' Twitter.module
' Support for sending tweets to twitter.com

' Development Status:
' Working.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

Public hTweet As Process

Public Sub PostTweet(sMessage As String) As Boolean

  Dim sCmd As String

  ' if not enabled, return
  If Not Main.bTwitterEnabled Then
    If Main.bTwitterDebug Then Main.WriteDebugLog(("[Twitter] You want to send a tweet '") & sMessage & ("' but the interface is disabled!"))
    Return
  Endif

  If Main.ProgramExist("bti") Then
    If Main.bTwitterTimeStamp Then sMessage = Format$(Now(), "hh:nn:ss ") & sMessage
    sCmd = "echo '" & sMessage & "'|bti"
    If Main.bTwitterDebug Then Main.WriteDebugLog(("[Twitter] Running '") & sCmd & "'")
    hTweet = Shell sCmd For Read As "Tweet"
  Else
    Main.WriteDebugLog(("[Twitter] You need to install the oauth library and bti command to use Twitter!"))
    Return False
  Endif

  Return True

End

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get process return value, 0 means ok, anything else is an error
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Public Sub Tweet_Kill()

  Dim iRc As Integer

  iRc = Last.Value
  If iRc Then
    Main.WriteDebugLog(("[Twitter] Error with return code ") & iRc)
  Else
    Main.WriteLog(("I have sent a Tweet to 'http://twitter.com/") & Main.sTwitterUser & "'.")
  Endif

End
