' Gambas module file

' Description:
' Twitter.module
' Support for sending tweets to twitter.com

' Development Status:
' Working.

' DomotiGa - an open source home automation program.
' Copyright (C) Ron Klinkien, The Netherlands.

' Read file called COPYING for license details.

PUBLIC hTweet AS Process

PUBLIC SUB PostTweet(sMessage AS String) AS Boolean

  ' if not enabled, return
  IF NOT Main.bTwitterEnabled THEN RETURN

  IF Main.ProgramExist("bti") THEN
    IF Main.bTwitterTimeStamp THEN sMessage = Format$(Now(), "hh:nn:ss ") & sMessage
    hTweet = SHELL "echo '" & sMessage & "'|bti" FOR READ AS "Tweet"
  ELSE
    Main.WriteLog(("You need to install the oauth library and bti cmd to use Twitter!"))
    RETURN FALSE
  ENDIF

  RETURN TRUE

END

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' get process return value, 0 means ok, anything else is an error
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUBLIC SUB Tweet_Kill()

  DIM iRc AS Integer

  iRc = LAST.Value
  IF iRc THEN
    Main.WriteDebugLog(("[Twitter] Error return code is ") & iRc)
  ELSE
    Main.WriteLog(("I have sent a Tweet to 'http://twitter.com/") & Main.sTwitterUser & "'.")
  ENDIF

END
